### DISCUSSION TITLE
Use Dimensions with CosmosDB provider

### DISCUSSION THREAD

**Discussion by matthieu-eck** [tomkerkhove/promitor#1084] [Q&A] [answered]
I would like to know if it is possible to scrape `muti-dimensional` metric on CosmosDb. I did not managed to make it work, I get always the Data Size of the whole CosmosDb instance, not per database size.

I checked the documentation and tried the following:
```
metrics: 
  - name: azure_cosmosdb_data_usage_total
    description: "Total data usage"
    resourceType: CosmosDb
    azureMetricConfiguration:
      metricName: DataUsage
      dimension:
        Name: DatabaseName
      aggregation:
        type: Total
    resources:
    - dbName: <DB-INSTANCE-NAME>
```
I would like to get the `DataUsage` per `Database`, as seen in this example (`Data Size`):
![image](https://user-images.githubusercontent.com/9448406/84170388-ec460d00-aa79-11ea-8a03-2d084c3efc44.png)

Is it possible to get these metrics with Promitor? Thanks!
