### DISCUSSION TITLE
Question about resource discovery of new & deleted VMs

### DISCUSSION THREAD

**Discussion by skuby2** [tomkerkhove/promitor#1243] [Q&A] [answered]
Hi. I ran across this software today and am very excited about it for some projects I have. Thank you very much for the great work. The question I have is about VMs that come and go. In my use case I am dynamically spinning up and tearing down VMs. I'm setup to use Prometheus. What I've seen is that new VMs are not shown in Prometheus and Grafana until I restart the promitor-agent-scraper container. Likewise, if promitor-agent-scraper is started while a VM is present and then I delete it, the VM does not go away until I restart promitor-agent-scraper again. In the later case it continues to report old metrics.

Is that the intent for how promitor-agent-scraper and promitor-agent-discovery should behave? Or is the intent (current or eventual) to handle new and deleted VMs, and it just isn't implemented yet?

A bit more info about my setup. Here's a basic outline of a script that shows how I'm running things.
Here are the version of software I'm using:

- Prometheus: 2.4.3
- promitor-agent-discovery: 0.1.0-preview-1 (which I think is the latest, except for CI builds)
- promitor-agent-scraper: 2.0.0-preview-2 (which I think is the latest, except for CI builds)

```
APP_ID=omit
APP_SECRET=omit
TENANT_ID=omit
SUBSCRIPTION_ID=omit
RESOURCE_GROUP=omit
CONFIG_DIR=~/promitor_configs
SCRAPER_PORT=8999
DISCOVERY_PORT=8998

rm -fr $CONFIG_DIR
mkdir -p $CONFIG_DIR

cat > $CONFIG_DIR/scrape-auth.creds << EOF
PROMITOR_AUTH_APPID=$APP_ID
PROMITOR_AUTH_APPKEY=$APP_SECRET
EOF

cat > $CONFIG_DIR/scrape-metrics.yaml << EOF
version: v1
azureMetadata:
  tenantId: $TENANT_ID
  subscriptionId: $SUBSCRIPTION_ID
  resourceGroupName: $RESOURCE_GROUP
metricDefaults:
  aggregation:
    interval: 00:05:00
  scraping:
    # Every minute
    schedule: "0 * * ? * *"
metrics:
  - name: azure_vm_percentage_cpu
    description: "Average percentage cpu usage on an Azure virtual machine"
    resourceType: VirtualMachine
    azureMetricConfiguration:
      metricName: Percentage CPU
      aggregation:
        type: Average
    resourceDiscoveryGroups:
    - name: vms
  - name: azure_vm_network_in
    description: "The number of bytes received on all network interfaces by the Virtual Machine(s) (Incoming Traffic)"
    resourceType: VirtualMachine
    azureMetricConfiguration:
      metricName: Network In Total
      aggregation:
        type: Average
    resourceDiscoveryGroups:
    - name: vms
  - name: azure_vm_network_out
    description: "The number of bytes out on all network interfaces by the Virtual Machine(s) (Outgoing Traffic)"
    resourceType: VirtualMachine
    azureMetricConfiguration:
      metricName: Network Out Total
      aggregation:
        type: Average
    resourceDiscoveryGroups:
    - name: vms
  - name: azure_vm_outbound_flows
    description: "Outbound Flows are number of current flows in the outbound direction (traffic going out of the VM)"
    resourceType: VirtualMachine
    azureMetricConfiguration:
      metricName: Outbound Flows
      aggregation:
        type: Average
    resourceDiscoveryGroups:
    - name: vms
EOF

cat > $CONFIG_DIR/scrape-runtime.yaml << EOF
server:
  httpPort: 80
metricSinks:
  prometheusScrapingEndpoint:
    metricUnavailableValue: NaN
    enableMetricTimestamps: true # true by default
    baseUriPath: /metrics
metricsConfiguration:
  absolutePath: /config/metrics-declaration.yaml
telemetry:
  applicationInsights:
    instrumentationKey: ABC
    isEnabled: false
    verbosity: warning
  containerLogs:
    isEnabled: true
    verbosity: trace
  defaultVerbosity: trace
azureMonitor:
  logging:
    isEnabled: false
resourceDiscovery:
  host: 172.18.0.1
  port: $DISCOVERY_PORT
EOF

cat > $CONFIG_DIR/discovery-auth.creds << EOF
PROMITOR_DISCOVERY_APPID=$APP_ID
PROMITOR_DISCOVERY_APPSECRET=$APP_SECRET
EOF

cat > $CONFIG_DIR/discovery-declaration.yaml << EOF
version: v1
azureLandscape:
  tenantId: $TENANT_ID
  subscriptions:
  - $SUBSCRIPTION_ID
  cloud: Global
resourceDiscoveryGroups:
- name: vms
  type: VirtualMachine
EOF

cat > $CONFIG_DIR/discovery-runtime.yaml << EOF
server:
  httpPort: 80
telemetry:
  applicationInsights:
    instrumentationKey: ABC
    isEnabled: false
    verbosity: warning
  containerLogs:
    isEnabled: true
    verbosity: trace
  defaultVerbosity: trace
EOF

docker run -d --rm -p $DISCOVERY_PORT:80 --name promitor-agent-resource-discovery                                    \
                         --env PROMITOR_DISCOVERY_APPID=$APP_ID                                                      \
                         --env-file $CONFIG_DIR/discovery-auth.creds                                                 \
                         --volume $CONFIG_DIR/discovery-declaration.yaml:/config/resource-discovery-declaration.yaml \
                         --volume $CONFIG_DIR/discovery-runtime.yaml:/config/runtime.yaml                            \
                         tomkerkhove/promitor-agent-discovery:0.1.0-preview-1

docker run -d --rm -p $SCRAPER_PORT:80 --name promitor-agent-scraper                                                 \
                         --env PROMITOR_AUTH_APPID=$APP_ID                                                           \
                         --env-file $CONFIG_DIR/scrape-auth.creds                                                    \
                         --volume $CONFIG_DIR/scrape-metrics.yaml:/config/metrics-declaration.yaml                   \
                         --volume $CONFIG_DIR/scrape-runtime.yaml:/config/runtime.yaml                               \
                         tomkerkhove/promitor-agent-scraper:2.0.0-preview-2
```
