### DISCUSSION TITLE
Azure Monitor Metrics

### DISCUSSION THREAD

**Discussion by wadhahbenaissa** [tomkerkhove/promitor#1340] [Q&A] [answered]
hello.
I was wondering what would be the configuration (metrics-decalaration.yaml) that would allow me to get all the metrics of a specific azure resource? for example get all the metrics of all the VMs existing in 1 or multi azure subscriptions?
thanks

**Comment by tomkerkhove** [comment, marked as answer]
You'll have to combine the upcoming resource discovery in v2.0 (but you can give it a try already with https://github.com/tomkerkhove/promitor/releases/tag/2.0.0-preview-3) and listing all the metrics in your metrics-decalaration.yaml that uses that resource discovery group.

We do not provide a metrics "wildcard" that scrapes all metrics for a given Azure resource, for now. Reason for that is throttling done by Azure, if we do that than you'll hit them (too) easily.

What we recommend is going to https://docs.microsoft.com/en-us/azure/azure-monitor/platform/metrics-supported, list the metrics you need and include them in your metrics declaration.

Hope this clarifies things?

**Reply by wadhahbenaissa** [reply]
I am using helm to install promitor on my AKS.
v2 for promitor did not work for me. The agent-scraper pod was all the time crashing and I'm afraid the logs were not comprehensive.
I had to run the stable helm chart version 1.6.0 with image version 1.6.1 to make promitor work.

**Reply by tomkerkhove** [reply]
Would you mind opening an issue with the logs please? Then we'll need to fix that.

With v1.x this will not be possible; sorry.

**Reply by wadhahbenaissa** [reply]
yep I saw that in the documentation.
okay then, will open an issue for this
and thanks a lot for your quick interactions.

**Reply by tomkerkhove** [reply]
My pleasure! I don't know if it answers your question, but feel free to mark it as answered if I did.

**Reply by wadhahbenaissa** [reply]
one final question if you please.
I am trying to have metrics scraped by promitor to get collected by prometheus.
I have upgraded prometheus installation with this config:
```
extraScrapeConfigs: |
  - job_name: promitor-agent-scraper
    metrics_path: /metrics
    static_configs:
      - targets:
        - my_service:8888
```
the promitor service looks as below:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "88"
    prometheus.io/scrape: "true"
  creationTimestamp: "2020-11-10T10:24:41Z"
  labels:
    app: promitor-agent-scraper
    chart: promitor-agent-scraper-1.6.0
    heritage: Helm
    release: promitor-agent-scraper
    type: infrastructure
  name: promitor-agent-scraper
  namespace: my_namespace
  resourceVersion: "4423"
  selfLink: /api/v1/namespaces/my_namespace/services/promitor-agent-scraper
  uid: f8fa4d8b-1f1a-4286-9189-33a10ab1de7e
spec:
  clusterIP: ****
  ports:
  - name: http
    port: 8888
    protocol: TCP
    targetPort: 88
  selector:
    app: promitor-agent-scraper
    release: promitor-agent-scraper
    type: runtime
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```
And I am trying to create a servicemonitor so that promitor becomes a prometheus target:
```
#Service Monitor for Promitor Exporter
apiVersion: monitoring.coreos.com/v1  
kind: ServiceMonitor
metadata:
  labels:
    app: promitor-agent-scraper
    chart: promitor-agent-scraper-1.6.0   
    heritage: Helm
    release: promitor-agent-scraper       
    type: infrastructure
  name: promitor-agent-scraper
  namespace: my_namespace
spec:
  endpoints:
  - path: '/metrics'
    port: http
  namespaceSelector:
    matchNames:
    - my_namespace
  selector:
    matchLabels:
      app: promitor-agent-scraper
      release: prometheus
      #chart: promitor-agent-scraper-1.6.0
      #heritage: Helm
      #type: infrastructure
```
I was wondering whether you've an idea what may be the issue, as I can't see promitor-agent-scraper as a target in prometheus.
Thanks in advance
