### DISCUSSION TITLE
Promitor x Helm 3 Deployment

### DISCUSSION THREAD

**Discussion by msftkenneth** [tomkerkhove/promitor#1397] [Q&A] [answered]
Hi,

I would like to know whether there is any extra settings for the metric declaration file for spinning up the scraper agent.
And I used the following yaml file for the scraper, however I got the errors shown below.

**`Definition File`**
```
azureMetadata:
  tenantId: <<redacted>>
  subscriptionId: <<redacted>>
  resourceGroupName: sample-rg
azureAuthentication:
  appId: "<<redacted>>"
  appKey: "<<redacted>>"
metricSinks:
  prometheusScrapingEndpoint:
    enabled: true
    baseUriPath: /metrics
    enableMetricTimestamps: true
metricDefaults:
  aggregation:
    interval: 00:05:00
  scraping:
    # Every minute
    schedule: "0 * * ? * *"
metrics:
  - name: azure_queue_message_count
    description: "The number of pending queue messages."
    resourceType: StorageQueue
    scraping:
      # Every 2 minutes
      schedule: "0 */2 * ? * *"
    azureMetricConfiguration:
      metricName: MessageCount
      aggregation:
        type: Average
    resources:
      - accountName: samplesacct
        queueName: test
        sasToken:
          rawValue: "<<redacted>>"
```

**`Error Log`**
```
> kubectl logs promitor-agent-scraper-595b8987bf-652ng promitor-agent-scraper
██████╗ ██████╗  ██████╗ ███╗   ███╗██╗████████╗ ██████╗ ██████╗
██╔══██╗██╔══██╗██╔═══██╗████╗ ████║██║╚══██╔══╝██╔═══██╗██╔══██╗
██████╔╝██████╔╝██║   ██║██╔████╔██║██║   ██║   ██║   ██║██████╔╝
██╔═══╝ ██╔══██╗██║   ██║██║╚██╔╝██║██║   ██║   ██║   ██║██╔══██╗
██║     ██║  ██║╚██████╔╝██║ ╚═╝ ██║██║   ██║   ╚██████╔╝██║  ██║
╚═╝     ╚═╝  ╚═╝ ╚═════╝ ╚═╝     ╚═╝╚═╝   ╚═╝    ╚═════╝ ╚═╝  ╚═╝

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Promitor.Scraper.Host.Startup..ctor(IConfiguration configuration) in /src/Promitor.Scraper.Host/Startup.cs:line 20
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetServiceOrCreateInstance(IServiceProvider provider, Type type)
   at Microsoft.AspNetCore.Hosting.Internal.StartupLoader.LoadMethods(IServiceProvider hostingServiceProvider, Type startupType, String environmentName)
   at Microsoft.AspNetCore.Hosting.WebHostBuilderExtensions.<>c__DisplayClass1_0.<UseStartup>b__1(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureStartup()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Promitor.Scraper.Host.Program.BuildWebHost(String[] args) in /src/Promitor.Scraper.Host/Program.cs:line 31
   at Promitor.Scraper.Host.Program.Main(String[] args) in /src/Promitor.Scraper.Host/Program.cs:line 16
```

Thanks,
Kenneth

**Comment by tomkerkhove** [comment, marked as answer]
I'll take a look at it but feel free to share your Deployment & ConfigMap in Kubernetes in meantime which would help with troubleshooting. Thanks!

**Reply by msftkenneth** [reply]
I found that it may conflict with Istio components when putting into the same cluster.

**Reply by tomkerkhove** [reply]
Feel free to share the Deployment & ConfigMap and I can help you take a closer look, normally Istio should not interrupt Promitor.

**Reply by msftkenneth** [reply]
**ConfigMap Details**
```
kubectl describe configmap config-map-promitor-agent-scraper
Name:         config-map-promitor-agent-scraper
Namespace:    default
Labels:       app=promitor-agent-scraper
              app.kubernetes.io/managed-by=Helm
              chart=promitor-agent-scraper-1.6.0
              heritage=Helm
              release=promitor-agent-scraper
Annotations:  meta.helm.sh/release-name: promitor-agent-scraper
              meta.helm.sh/release-namespace: default

Data
====
metrics-declaration.yaml:
----
version: v1
azureMetadata:
  tenantId: <redacted>
  subscriptionId: <redacted>
  resourceGroupName: <redacted>
metricDefaults:
  aggregation:
    interval: 00:05:00
  scraping:
    schedule: "0 * * ? * *"
metrics:
- azureMetricConfiguration:
    aggregation:
      type: Average
    metricName: MessageCount
  description: The number of pending queue messages.
  name: azure_queue_message_count
  resourceType: StorageQueue
  resources:
  - accountName: <redacted>
    queueName: test
    sasToken:
      rawValue: <redacted>
  scraping:
    schedule: 0 */2 * ? * *
runtime.yaml:
----
server:
  httpPort: "88"
metricSinks:
  prometheusScrapingEndpoint:
    metricUnavailableValue: "NaN"
    enableMetricTimestamps: "true"
    baseUriPath: "/metrics"
metricsConfiguration:
  absolutePath: /config/metrics-declaration.yaml
telemetry:
  applicationInsights:
    isEnabled: "false"
  containerLogs:
    isEnabled: "true"
  defaultVerbosity: "Error"
Events:  <none>
```


**Deployment Details**
```
kubectl describe deployment promitor-agent-scraper
Name:                   promitor-agent-scraper
Namespace:              default
CreationTimestamp:      Mon, 07 Dec 2020 18:08:58 +0800
Labels:                 app=promitor-agent-scraper
                        app.kubernetes.io/managed-by=Helm
                        chart=promitor-agent-scraper-1.6.0
                        heritage=Helm
                        release=promitor-agent-scraper
Annotations:            deployment.kubernetes.io/revision: 1
                        meta.helm.sh/release-name: promitor-agent-scraper
                        meta.helm.sh/release-namespace: default
Selector:               app=promitor-agent-scraper,release=promitor-agent-scraper,type=runtime
Replicas:               1 desired | 1 updated | 1 total | 0 available | 1 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  1 max unavailable, 1 max surge
Pod Template:
  Labels:           app=promitor-agent-scraper
                    release=promitor-agent-scraper
                    type=runtime
  Annotations:      checksum/config: 392d192a1a1a7f1133eb88711407ed8003bef7888d1e5434c6394db02169ceef
                    checksum/secret: 16cfaa298a2b2a5a1bae98d10ed2968e23879ed20e79dca907576a2e7f83be1c
  Service Account:  promitor-agent-scraper
  Containers:
   promitor-agent-scraper:
    Image:      tomkerkhove/promitor-agent-scraper:1.0.0
    Port:       88/TCP
    Host Port:  0/TCP
    Liveness:   http-get http://:http/api/v1/health delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:  http-get http://:http/api/v1/health delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      PROMITOR_AUTH_APPID:   <set to the key 'azure-app-id' in secret 'promitor-agent-scraper'>   Optional: false
      PROMITOR_AUTH_APPKEY:  <set to the key 'azure-app-key' in secret 'promitor-agent-scraper'>  Optional: false
    Mounts:
      /config/ from config-volume-promitor-agent-scraper (rw)
  Volumes:
   config-volume-promitor-agent-scraper:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      config-map-promitor-agent-scraper
    Optional:  false
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    ReplicaSetUpdated
OldReplicaSets:  <none>
NewReplicaSet:   promitor-agent-scraper-595b8987bf (1/1 replicas created)
Events:
  Type    Reason             Age    From                   Message
  ----    ------             ----   ----                   -------
  Normal  ScalingReplicaSet  4m39s  deployment-controller  Scaled up replica set promitor-agent-scraper-595b8987bf to 1
```


**Scraper Pod Details**
```
kubectl describe pod promitor-agent-scraper-595b8987bf-6g4j2
Name:         promitor-agent-scraper-595b8987bf-6g4j2
Namespace:    default
Priority:     0
Node:         aks-agentpool01-26063383-vmss000000/10.0.5.4
Start Time:   Mon, 07 Dec 2020 18:08:59 +0800
Labels:       app=promitor-agent-scraper
              istio.io/rev=default
              pod-template-hash=595b8987bf
              release=promitor-agent-scraper
              security.istio.io/tlsMode=istio
              service.istio.io/canonical-name=promitor-agent-scraper
              service.istio.io/canonical-revision=latest
              type=runtime
Annotations:  checksum/config: 392d192a1a1a7f1133eb88711407ed8003bef7888d1e5434c6394db02169ceef
              checksum/secret: 16cfaa298a2b2a5a1bae98d10ed2968e23879ed20e79dca907576a2e7f83be1c
              prometheus.io/path: /stats/prometheus
              prometheus.io/port: 15020
              prometheus.io/scrape: true
              sidecar.istio.io/status:
                {"version":"e2cb9d4837cda9584fd272bfa1f348525bcaacfadb7e9b9efbd21a3bb44ad7a1","initContainers":["istio-init"],"containers":["istio-proxy"]...
Status:       Running
IP:           10.0.5.12
IPs:
  IP:           10.0.5.12
Controlled By:  ReplicaSet/promitor-agent-scraper-595b8987bf
Init Containers:
  istio-init:
    Container ID:  docker://86cb5dd2fc163f587f79bc54f252ae3c68e18339fb9b12ded304cbe9eba86232
    Image:         docker.io/istio/proxyv2:1.8.0
    Image ID:      docker-pullable://istio/proxyv2@sha256:8721ddb5acf86dbe9d4c68993947c27d4b98a6d23ecde80246c74bf8bebd163f
    Port:          <none>
    Host Port:     <none>
    Args:
      istio-iptables
      -p
      15001
      -z
      15006
      -u
      1337
      -m
      REDIRECT
      -i
      *
      -x

      -b
      *
      -d
      15090,15021,15020
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Mon, 07 Dec 2020 18:09:02 +0800
      Finished:     Mon, 07 Dec 2020 18:09:02 +0800
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     2
      memory:  1Gi
    Requests:
      cpu:     10m
      memory:  40Mi
    Environment:
      DNS_AGENT:
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from promitor-agent-scraper-token-2npbk (ro)
Containers:
  promitor-agent-scraper:
    Container ID:   docker://b8d86e9f94ee0f784f6b7b09aa8253738e414dc4479426fc9e3e8657f7a0ee73
    Image:          tomkerkhove/promitor-agent-scraper:1.0.0
    Image ID:       docker-pullable://tomkerkhove/promitor-agent-scraper@sha256:c42961e992539dca356108580ec8eacdf1263b07928276ed6331e90318d9ab21
    Port:           88/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    139
      Started:      Mon, 07 Dec 2020 18:09:32 +0800
      Finished:     Mon, 07 Dec 2020 18:09:32 +0800
    Ready:          False
    Restart Count:  2
    Liveness:       http-get http://:15020/app-health/promitor-agent-scraper/livez delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:      http-get http://:15020/app-health/promitor-agent-scraper/readyz delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      PROMITOR_AUTH_APPID:   <set to the key 'azure-app-id' in secret 'promitor-agent-scraper'>   Optional: false
      PROMITOR_AUTH_APPKEY:  <set to the key 'azure-app-key' in secret 'promitor-agent-scraper'>  Optional: false
    Mounts:
      /config/ from config-volume-promitor-agent-scraper (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from promitor-agent-scraper-token-2npbk (ro)
  istio-proxy:
    Container ID:  docker://f62b7620c30992c673faad6c04d10755cc47c55a80259d7a525cb230fdbc985e
    Image:         docker.io/istio/proxyv2:1.8.0
    Image ID:      docker-pullable://istio/proxyv2@sha256:8721ddb5acf86dbe9d4c68993947c27d4b98a6d23ecde80246c74bf8bebd163f
    Port:          15090/TCP
    Host Port:     0/TCP
    Args:
      proxy
      sidecar
      --domain
      $(POD_NAMESPACE).svc.cluster.local
      --serviceCluster
      promitor-agent-scraper.$(POD_NAMESPACE)
      --proxyLogLevel=warning
      --proxyComponentLogLevel=misc:error
      --concurrency
      2
    State:          Running
      Started:      Mon, 07 Dec 2020 18:09:08 +0800
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     2
      memory:  1Gi
    Requests:
      cpu:      10m
      memory:   40Mi
    Readiness:  http-get http://:15021/healthz/ready delay=1s timeout=3s period=2s #success=1 #failure=30
    Environment:
      JWT_POLICY:                    third-party-jwt
      PILOT_CERT_PROVIDER:           istiod
      CA_ADDR:                       istiod.istio-system.svc:15012
      POD_NAME:                      promitor-agent-scraper-595b8987bf-6g4j2 (v1:metadata.name)
      POD_NAMESPACE:                 default (v1:metadata.namespace)
      INSTANCE_IP:                    (v1:status.podIP)
      SERVICE_ACCOUNT:                (v1:spec.serviceAccountName)
      HOST_IP:                        (v1:status.hostIP)
      CANONICAL_SERVICE:              (v1:metadata.labels['service.istio.io/canonical-name'])
      CANONICAL_REVISION:             (v1:metadata.labels['service.istio.io/canonical-revision'])
      PROXY_CONFIG:                  {"proxyMetadata":{"DNS_AGENT":""}}

      ISTIO_META_POD_PORTS:          [
                                         {"name":"http","containerPort":88,"protocol":"TCP"}
                                     ]
      ISTIO_META_APP_CONTAINERS:     promitor-agent-scraper
      ISTIO_META_CLUSTER_ID:         Kubernetes
      ISTIO_META_INTERCEPTION_MODE:  REDIRECT
      ISTIO_METAJSON_ANNOTATIONS:    {"checksum/config":"392d192a1a1a7f1133eb88711407ed8003bef7888d1e5434c6394db02169ceef","checksum/secret":"16cfaa298a2b2a5a1bae98d10ed2968e23879ed20e79dca907576a2e7f83be1c"}

      ISTIO_META_WORKLOAD_NAME:      promitor-agent-scraper
      ISTIO_META_OWNER:              kubernetes://apis/apps/v1/namespaces/default/deployments/promitor-agent-scraper
      ISTIO_META_MESH_ID:            cluster.local
      TRUST_DOMAIN:                  cluster.local
      DNS_AGENT:
      ISTIO_KUBE_APP_PROBERS:        {"/app-health/promitor-agent-scraper/livez":{"httpGet":{"path":"/api/v1/health","port":88,"scheme":"HTTP"},"timeoutSeconds":1},"/app-health/promitor-agent-scraper/readyz":{"httpGet":{"path":"/api/v1/health","port":88,"scheme":"HTTP"},"timeoutSeconds":1}}
    Mounts:
      /etc/istio/pod from istio-podinfo (rw)
      /etc/istio/proxy from istio-envoy (rw)
      /var/lib/istio/data from istio-data (rw)
      /var/run/secrets/istio from istiod-ca-cert (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from promitor-agent-scraper-token-2npbk (ro)
      /var/run/secrets/tokens from istio-token (rw)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  config-volume-promitor-agent-scraper:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      config-map-promitor-agent-scraper
    Optional:  false
  promitor-agent-scraper-token-2npbk:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  promitor-agent-scraper-token-2npbk
    Optional:    false
  istio-envoy:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  istio-data:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  istio-podinfo:
    Type:  DownwardAPI (a volume populated by information about the pod)
    Items:
      metadata.labels -> labels
      metadata.annotations -> annotations
  istio-token:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  43200
  istiod-ca-cert:
    Type:        ConfigMap (a volume populated by a ConfigMap)
    Name:        istio-ca-root-cert
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                From                                          Message
  ----     ------     ----               ----                                          -------
  Normal   Scheduled  <unknown>          default-scheduler                             Successfully assigned default/promitor-agent-scraper-595b8987bf-6g4j2 to aks-agentpool01-26063383-vmss000000
  Normal   Pulling    60s                kubelet, aks-agentpool01-26063383-vmss000000  Pulling image "docker.io/istio/proxyv2:1.8.0"
  Normal   Pulled     57s                kubelet, aks-agentpool01-26063383-vmss000000  Successfully pulled image "docker.io/istio/proxyv2:1.8.0"
  Normal   Created    57s                kubelet, aks-agentpool01-26063383-vmss000000  Created container istio-init
  Normal   Started    57s                kubelet, aks-agentpool01-26063383-vmss000000  Started container istio-init
  Normal   Pulling    54s                kubelet, aks-agentpool01-26063383-vmss000000  Pulling image "docker.io/istio/proxyv2:1.8.0"
  Normal   Created    51s                kubelet, aks-agentpool01-26063383-vmss000000  Created container istio-proxy
  Normal   Started    51s                kubelet, aks-agentpool01-26063383-vmss000000  Started container istio-proxy
  Normal   Pulled     51s                kubelet, aks-agentpool01-26063383-vmss000000  Successfully pulled image "docker.io/istio/proxyv2:1.8.0"
  Warning  Unhealthy  49s                kubelet, aks-agentpool01-26063383-vmss000000  Readiness probe failed: Get http://10.0.5.12:15021/healthz/ready: dial tcp 10.0.5.12:15021: connect: connection refused
  Normal   Pulling    30s (x3 over 57s)  kubelet, aks-agentpool01-26063383-vmss000000  Pulling image "tomkerkhove/promitor-agent-scraper:1.0.0"
  Normal   Created    27s (x3 over 54s)  kubelet, aks-agentpool01-26063383-vmss000000  Created container promitor-agent-scraper
  Normal   Started    27s (x3 over 54s)  kubelet, aks-agentpool01-26063383-vmss000000  Started container promitor-agent-scraper
  Normal   Pulled     27s (x3 over 54s)  kubelet, aks-agentpool01-26063383-vmss000000  Successfully pulled image "tomkerkhove/promitor-agent-scraper:1.0.0"
  Warning  BackOff    26s (x4 over 46s)  kubelet, aks-agentpool01-26063383-vmss000000  Back-off restarting failed container
```
