### DISCUSSION TITLE
Issue fetching EventHubDroppedEvents using Generic metric declaration.

### DISCUSSION THREAD

**Discussion by agmimidi** [tomkerkhove/promitor#1538] [General] [answered]
Hi.

I am trying to fetch the Dropped events from an _ApiManagementService_ resource. Using the following configuration. (resource group is inherited from the block _AzureMetadata_).

```
  - name: azApiDroppedEvents
    description: "Number of events skipped because of queue size limit reached"
    resourceType: Generic
    azureMetricConfiguration:
      metricName: EventHubDroppedEvents
      aggregation:
        type: Total
    resources:
    - resourceUri: Microsoft.ApiManagement/service/{confidential}
```
But I keep getting the following error:
```
promitor-agent-scraper-5bd6b57b89-4vf5h:System.ArgumentException: [details cannot be Null, empty or white-space. (Parameter 'details')
promitor-agent-scraper-5bd6b57b89-4vf5h:   at GuardNet.Guard.For[TException(Func`1 predicate, TException exception)
promitor-agent-scraper-5bd6b57b89-4vf5h:   at GuardNet.Guard.NotNullOrWhitespace[TException(String param, TException exception)
promitor-agent-scraper-5bd6b57b89-4vf5h:   at GuardNet.Guard.NotNullOrWhitespace(String param, String paramName, String message)
promitor-agent-scraper-5bd6b57b89-4vf5h:   at GuardNet.Guard.NotNullOrWhitespace(String param, String paramName)
promitor-agent-scraper-5bd6b57b89-4vf5h:   at Promitor.Integrations.AzureMonitor.Exceptions.MetricInformationNotFoundException..ctor(String name, String details, String dimension) in /src/Promitor.Integrations.AzureMonitor/MetricInformationNotFoundException.cs:line 33
promitor-agent-scraper-5bd6b57b89-4vf5h:   at Promitor.Integrations.AzureMonitor.AzureMonitorClient.QueryMetricAsync(String metricName, String metricDimension, AggregationType aggregationType, TimeSpan aggregationInterval, String resourceId, String metricFilter) in /src/Promitor.Integrations.AzureMonitor/AzureMonitorClient.cs:line 85
promitor-agent-scraper-5bd6b57b89-4vf5h:   at Promitor.Core.Scraping.AzureMonitorScraper`1.ScrapeResourceAsync(String subscriptionId, ScrapeDefinition`1 scrapeDefinition, TResourceDefinition resourceDefinition, AggregationType aggregationType, TimeSpan aggregationInterval) in /src/Promitor.Core.Scraping/AzureMonitorScraper.cs:line 51
promitor-agent-scraper-5bd6b57b89-4vf5h:   at Promitor.Core.Scraping.Scraper`1.ScrapeAsync(ScrapeDefinition`1 scrapeDefinition) in /src/Promitor.Core.Scraping/Scraper.cs:line 70
```
The Promitor deployment is on a k8s cluster and has been deployed using Helm .
Container version is v2.1.0
I am also collecting other metrics (Generic and targeted) without any issues. So (I think) the configuration of Promitor is correct.

Cheers and thanks for a great product
Angelos
