### DISCUSSION TITLE
Filter / split multi-dimensional Azure Application Gateway metrics

### DISCUSSION THREAD

**Discussion by DaveOHenry** [tomkerkhove/promitor#1591] [Q&A] [answered]
I am currently trying to get the count of http responses by backend **and** status code.  https://docs.microsoft.com/en-us/azure/azure-monitor/essentials/metrics-supported#microsoftnetworkapplicationgateways

I tried the following, but no luck so far:
```
metrics:
  - name: azure_application_gateway_backend_response_status
    description: "Http responses of Azure Application Gateway by backend and status code"
    resourceType: Generic
    azureMetricConfiguration:
      metricName: BackendResponseStatus
      aggregation:
        type: Total
      dimension:
        name: BackendPool
    resources:
      - resourceUri: Microsoft.Network/applicationGateways/my-appgw1234
        filter: HttpStatusGroup eq '1xx'
      - resourceUri: Microsoft.Network/applicationGateways/my-appgw1234
        filter: HttpStatusGroup eq '2xx'
      - resourceUri: Microsoft.Network/applicationGateways/my-appgw1234
        filter: HttpStatusGroup eq '3xx'
      - resourceUri: Microsoft.Network/applicationGateways/my-appgw1234
        filter: HttpStatusGroup eq '4xx'
      - resourceUri: Microsoft.Network/applicationGateways/my-appgw1234
        filter: HttpStatusGroup eq '5xx'
```

Is this possible somehow? I guess I'm doing it wrong somewhere. Applying a filter like this in the portal works fine, but it looks like Promitor can't find any data with my configuration. There is no error in the logs however.

**Comment by tomkerkhove** [comment, marked as answer]
Odd. Can you enable the Azure Monitor logging please?

What version are you running?

**Reply by DaveOHenry** [reply]
Thanks a lot. The version is 
```
app.kubernetes.io/version: 2.1.0
helm.sh/chart: promitor-agent-scraper-2.2.1
```

I activated logging with:
```
    telemetry:
      applicationInsights:
        isEnabled: "false"
      containerLogs:
        isEnabled: "true"
        verbosity: "trace"
      defaultVerbosity: "Error"
    azureMonitor:
      logging:
        informationLevel: "BodyAndHeaders"
        isEnabled: "true"
```

... in runtime.yaml and saw that the resources were using the default resource group. I had to override it and also split the metric declaration:

```
metrics:
  - name: azure_application_gateway_backend_response_status_1xx
    description: "Http responses of Azure Application Gateway by backend and status code"
    resourceType: Generic
    azureMetricConfiguration:
      metricName: BackendResponseStatus
      aggregation:
        type: Total
      dimension:
        name: BackendPool
    resources:
      - resourceUri: Microsoft.Network/applicationGateways/my-appgw1234
        resourceGroupName: my-rg
        filter: HttpStatusGroup eq '1xx'
  - name: azure_application_gateway_backend_response_status_2xx
    description: "Http responses of Azure Application Gateway by backend and status code"
    resourceType: Generic
    azureMetricConfiguration:
      metricName: BackendResponseStatus
      aggregation:
        type: Total
      dimension:
        name: BackendPool
    resources:
      - resourceUri: Microsoft.Network/applicationGateways/my-appgw1234
        resourceGroupName: my-rg
        filter: HttpStatusGroup eq '2xx'
  - name: azure_application_gateway_backend_response_status_3xx
    description: "Http responses of Azure Application Gateway by backend and status code"
    resourceType: Generic
    azureMetricConfiguration:
      metricName: BackendResponseStatus
      aggregation:
        type: Total
      dimension:
        name: BackendPool
    resources:
      - resourceUri: Microsoft.Network/applicationGateways/my-appgw1234
        resourceGroupName: my-rg
        filter: HttpStatusGroup eq '3xx'
  - name: azure_application_gateway_backend_response_status_4xx
    description: "Http responses of Azure Application Gateway by backend and status code"
    resourceType: Generic
    azureMetricConfiguration:
      metricName: BackendResponseStatus
      aggregation:
        type: Total
      dimension:
        name: BackendPool
    resources:
      - resourceUri: Microsoft.Network/applicationGateways/my-appgw1234
        resourceGroupName: my-rg
        filter: HttpStatusGroup eq '4xx'
  - name: azure_application_gateway_backend_response_status_5xx
    description: "Http responses of Azure Application Gateway by backend and status code"
    resourceType: Generic
    azureMetricConfiguration:
      metricName: BackendResponseStatus
      aggregation:
        type: Total
      dimension:
        name: BackendPool
    resources:
      - resourceUri: Microsoft.Network/applicationGateways/my-appgw1234
        resourceGroupName: my-rg
        filter: HttpStatusGroup eq '5xx'
```

It's returning metrics now, but it looks like the filter is not applied correctly. The value is exactly the same for every instance.

**Reply by tomkerkhove** [reply]
That's a step closer.

Odd that it's not filtering, would you mind sharing the Azure Monitor logs please?

**Reply by DaveOHenry** [reply]
Good to know that filtering *should* work this way, but something seems to be off. Without the above metrics configuration I can activate and view the Azure Monitor logs. As soon as I add the snippet from above there are no Azure Monitor logs anymore. This doesn't really make sense, but it looks like the scraper falls back to the default logging configuration somehow even though the runtime.yaml didn't change.

I guess I have to take a deeper look and test it in a clean environment.

**Reply by tomkerkhove** [reply]
What is your verbosity of telemetry?

**Reply by DaveOHenry** [reply]
This is the runtime.yaml:
```
server:
  httpPort: "88"
resourceDiscovery:
  host: "promitor-agent-resource-discovery.infrastructure"
  port: 8889
metricSinks:
  prometheusScrapingEndpoint:
    metricUnavailableValue: "NaN"
    enableMetricTimestamps: "true"
    baseUriPath: "/metrics"
metricsConfiguration:
  absolutePath: /config/metrics-declaration.yaml
telemetry:
  applicationInsights:
    isEnabled: "false"
  containerLogs:
    isEnabled: "true"
    verbosity: "trace"
  defaultVerbosity: "trace"
azureMonitor:              
  logging:                 
    informationLevel: "Basic"
    isEnabled: "true"
```
