### DISCUSSION TITLE
How can I query a metric with an Azure Monitor filter?

### DISCUSSION THREAD

**Discussion by salehabbas** [tomkerkhove/promitor#1601] [Q&A] [answered]
Hello Team, 

Thanks for that super nice and helpful tool! I have just started playing with it today and I wanted to ask a question, please. 

According to _Azure Documentation_:

**Application Gateway**:
- **BackendResponseStatus** : Count of HTTP response status codes returned by the backends. This does not include any response codes generated by the Application Gateway. **_The response status code distribution can be further categorized to show responses in 2xx, 3xx, 4xx, and 5xx categories_**.

That's easy to do using **_Azure Monitor_** **_from the Portal_**.  You choose the metric and then **_add a filter_** (**Property**/**Operator**/**Value**) in order to be able to get further categorized metrics. I cannot find how to do with with promitor. 

An example of my configuration is:
```
  - name: azure_application_gateways_backend_response_status
    description: "Count of HTTP response status codes returned by the backends. This does not include any response codes generated by the Application Gateway"
    resourceType: ApplicationGateway
    azureMetricConfiguration:
      metricName: BackendResponseStatus
      aggregation:
        type: Total
    resourceDiscoveryGroups:
      - name: application-gateway-landscape
```
These configs reports **_the sum of everything_** which is actually not very helpful as I am interested in **_the numbers per response category (2xx, 3xx, 4xx, and 5xx)_**. 

I would appreciate your help with that.
