### DISCUSSION TITLE
Would it be helpful to make the metric name optional?

### DISCUSSION THREAD

**Discussion by salehabbas** [tomkerkhove/promitor#1605] [Ideas] [answered]
Hello Team, 

I would appreciate your feedback about **_a little suggestion_**, please. While trying Promitor (with _Prometheus_), I can see that the **_Metric Name_** is a **_required_** field. Would it helpful to make it optional and automatically construct the metric name for Prometheus sink as follow:
```
<azure>_<short_resource_name>_<azureMetricConfiguration.metricName>_<azureMetricConfiguration.aggregation.type> 
```

**_An example for clarification_**:
The metric name will be optional and is: ```azure_agw_backend_response_status_total```

And the **_metric definition_** is:
```
  - description: "Count of HTTP response status codes returned by the backends. This does not include any response codes generated by the Application Gateway"
    resourceType: ApplicationGateway
    azureMetricConfiguration:
      metricName: BackendResponseStatus
      aggregation:
        type: Total
    resourceDiscoveryGroups:
      - name: application-gateway-landscape
```

Just wanted to see if it's worth it and maybe I can work on a PR.
