### DISCUSSION TITLE
How to use metric defaults labels (metricDefaults.labels)?

### DISCUSSION THREAD

**Discussion by salehabbas** [tomkerkhove/promitor#1607] [Q&A] [answered]
Hello Team, 

While trying to apply some default labels to all metrics I have, I keep getting the following error:
```
[11:29:38 WRN] The following problems were found with the metric configuration:
Warning 7:3: Unknown field 'labels'.
```

My configurations are:
```
metricDefaults:
  labels:
    application: test
  aggregation:
    interval: 00:01:00
  scraping:
    schedule: "*/1 * * * *"
```

**_The custom labels only work when I set them per metric level_**, the following example works:
```
metrics:
  - name: azure_agw_current_connections_total
    labels:
      application: test
    description: "The total number of concurrent connections active from clients to the Application Gateway"
    resourceType: ApplicationGateway
    azureMetricConfiguration:
      metricName: CurrentConnections
      aggregation:
        type: Total
    resourceDiscoveryGroups:
      - name: application-gateway-landscape
```

I am running the latest container for the scraper: *promitor-agent-scraper:2.2.0*
