### DISCUSSION TITLE
Promitor exports metric with name Size to Prometheus that does not match the one in Azure Monitor

### DISCUSSION THREAD

**Discussion by esierrapena** [tomkerkhove/promitor#1609] [Q&A] [answered]
### Report

I have deployed the promitor scraper in a k8s cluster but metric "Size" of Eventhub resource exported to Prometheus doesn't match the one i can see in Azure Portal.

### Expected Behavior

Same metric in Azure portal as in Prometheus

### Actual Behavior

Different metric value

### Steps to Reproduce the Problem

1. Define configmap
```
apiVersion: v1
data:
  metrics-declaration.yaml: |-
    version: v1
    azureMetadata:
      tenantId: a5bXXXXXXXXXXXXXXXX4bf20
      subscriptionId: 8f17XXXXXXXXXXXXXX680e1e0
      resourceGroupName: test-northeurope
    metricDefaults:
      aggregation:
        interval: 00:01:00
      scraping:
        schedule: "* * * * *"
    metrics:
      - name: azure_eventhubs_size
        description: "Size of an EventHub in Bytes."
        resourceType: EventHubs
        azureMetricConfiguration:
          metricName: Size
          aggregation:
            type: Average
        resources:
          - namespace: test-eventhub-namespace-hgu
```
2. Check metrics in Grafana with Azure Monitor as datasource (Figure 1) and Prometheus as datasource (Figure 2). Figure 3 metrics in Azure portal
Figure 1
![image](https://user-images.githubusercontent.com/43673236/115895065-4bc2c680-a45a-11eb-9c45-fc8a52d082ca.png)
Figure 2
![image](https://user-images.githubusercontent.com/43673236/115895128-5da46980-a45a-11eb-931c-9a7afaceae54.png)
Figure 3
![image](https://user-images.githubusercontent.com/43673236/115895190-6d23b280-a45a-11eb-895e-997f76c65c79.png)

### Component

Scraper

### Version

2.0.0

### Configuration

Configuration:

```yaml
apiVersion: v1
data:
  metrics-declaration.yaml: |-
    version: v1
    azureMetadata:
      tenantId: a5bXXXXXXXXXXXXXXXX4bf20
      subscriptionId: 8f17XXXXXXXXXXXXXX680e1e0
      resourceGroupName: test-northeurope
    metricDefaults:
      aggregation:
        interval: 00:01:00
      scraping:
        schedule: "* * * * *"
    metrics:
      - name: azure_eventhubs_size
        description: "Size of an EventHub in Bytes."
        resourceType: EventHubs
        azureMetricConfiguration:
          metricName: Size
          aggregation:
            type: Average
        resources:
          - namespace: test-eventhub-namespace-hgu
```

### Platform

Microsoft Azure

**Comment by tomkerkhove** [comment]
Thanks for reporting, can you share the configuration of the graph in Azure Portal please? Does it also use the same aggregation as Promitor (`00:01:00`)?

**Comment by tomkerkhove** [comment]
Using 1 minute as an aggregation is also not ideal since Azure Monitor has a lag, so I'm not sure if this is related but better alignt the Azure Portal metrics with the Promitor configuration and verify.

Relates to https://github.com/tomkerkhove/promitor/issues/1290 & https://github.com/tomkerkhove/promitor/issues/1563

**Comment by esierrapena** [comment]
hi! seems to work with the recommended configuration, closing this issue..

**Comment by tomkerkhove** [comment]
Huh so it was just a difference in the aggregation then? Thanks for letting me know!

**Comment by esierrapena** [comment, marked as answer]
Now, seems to work well with both configuration as you can see below:

```
  metrics-declaration.yaml: |-
    version: v1
    azureMetadata:
      tenantId: xxxxx
      subscriptionId: xxxxxxxxxx
      resourceGroupName: xxxxxxx
    metricDefaults:
      aggregation:
        interval: 00:01:00
      scraping:
        schedule: "* * * * *"
    metrics:
      - name: azure_eventhubs_size
        description: "Size of an EventHub in Bytes."
        resourceType: EventHubs
        azureMetricConfiguration:
          metricName: Size
          aggregation:
            type: Average
          dimension:
            name: EntityName
        resources:
          - namespace: test-eventhub-namespace-hgu
  runtime.yaml: |-
    server:
      httpPort: 88
    metricSinks:
      prometheusScrapingEndpoint:
        metricUnavailableValue: "NaN"
        enableMetricTimestamps: "true"
        baseUriPath: "/metrics"
    metricsConfiguration:
      absolutePath: /config/metrics-declaration.yaml
    telemetry:
      containerLogs:
        isEnabled: "true"
      defaultVerbosity: "Error"
```
Metrics in grafana

![image](https://user-images.githubusercontent.com/43673236/116067555-88283980-a689-11eb-97d1-1c0b43eaacf8.png)

Metrics in Azure Portal

![image](https://user-images.githubusercontent.com/43673236/116067679-abeb7f80-a689-11eb-96ba-a3e5de5c2027.png)
