### DISCUSSION TITLE
Azure metric with multidimensions

### DISCUSSION THREAD

**Discussion by andreibogdan** [tomkerkhove/promitor#1687] [Q&A]
Hi,
If I want to scrap for a Availability metric with 3 dimensions from Microsoft.ClassicStorage/storageAccounts/blobServices how should I write the definition in promitor metrics?
I used something like:
```
- name: azure_storage_blob_availability
  description: "" 
  resourceType: BlobStorage
  azureMetricConfiguration:
    metricName: Availability
    aggregation:
      type: Average
    dimension:
      name: GeoType
  resources: 
  - accountName: foobar
- name: azure_storage_blob_availability_apiname
  description: "" 
  resourceType: BlobStorage
  azureMetricConfiguration:
    metricName: Availability
    aggregation:
      type: Average
    dimension:
      name: ApiName
  resources: 
  - accountName: foobar  
```

Is there any other aproach? This was the only one that works until now.
