### DISCUSSION TITLE
Promitor filter for Azure Generic resource is not working?

### DISCUSSION THREAD

**Discussion by karolflis-tomtom** [tomkerkhove/promitor#1736] [Q&A] [answered]
Hi guys.

Im trying to scrape SNAT ports metrics from Kubernetes Load balancer and that is working OK. However I cannot get "filter" field to work, no matter how i try. I tried it about dozen of different combination and it does simply not filter anything.

Example in documentation: https://docs.promitor.io/configuration/v2.x/metrics/generic-azure-resource

My example:
```
  - name: azure_kubernetes_load_balancer_snat_allocated_ports3
    description: "Amount of allocated SNAT ports"
    resourceType: Generic
    azureMetricConfiguration:
      metricName: AllocatedSnatPorts
      aggregation:
        type: Average
    resources:
    %{ for load_balancer in load_balancers }
    - resourceUri: Microsoft.Network/loadBalancers/${load_balancer.load_balancer_name}
      resourceGroupName: ${load_balancer.resource_group_name}
      filter: Protocol Type neq UDP
    %{ endfor ~}
```

I tried field filter with values like:
- Protocol Type neq UDP
- ProtocolType neq UDP
- any combination of quoting, double quoting, single quoting for individual words of "ProtocolType/Protocol Type", "UDP" as well as whole sentence.
- i tried to move "filter" field into "azureMetricConfiguration"

Has anyone managed to have it working? I spent several hours experimenting and im stuck.

I need to get metric and filter as on the screen: https://imgur.com/a/SakMP80
