### DISCUSSION TITLE
Giving more flexibility with the filter by tags

### DISCUSSION THREAD

**Discussion by locmai** [tomkerkhove/promitor#1779] [Ideas] [answered]
**Component:** Resource Discovery Group

We would love to have the ability to filter by tags that have the same key but with multiple values. For an example, right now we could only define the resource discovery like this:

```yaml
resourceDiscoveryGroups:
- name: filtered-logic-apps-landscape
  type: LogicApp
  criteria:
    include:
      subscriptions:
      - SUBSCRIPTON-ID-ABC
      resourceGroups:
      - promitor-resource-group-1
      tags:
        app: promitor
```
So if we had many LogicApp with the tag `app` and we just want some of them, we couldn't do it for now.

Some initial approaches I could think of:

Approach 1:
For now we have these lines explicitly define the condition `==` :
https://github.com/tomkerkhove/promitor/blob/e1fdb945a79a0a58b20411f7288ef98cc8c1e6f7/src/Promitor.Agents.ResourceDiscovery/Graph/Query/GraphQueryBuilder.cs#L160
https://github.com/tomkerkhove/promitor/blob/e1fdb945a79a0a58b20411f7288ef98cc8c1e6f7/src/Promitor.Agents.ResourceDiscovery/Graph/Query/GraphQueryBuilder.cs#L164

So my naive thought is changing that to `=~` for regular expression match, and the configuration would be like this:

```yaml
      tags:
        app: promitor|argocd
```

Approach 2:
Re-use the FilterByField the same way as other filter like subscriptions/resource groups:
https://github.com/tomkerkhove/promitor/blob/e1fdb945a79a0a58b20411f7288ef98cc8c1e6f7/src/Promitor.Agents.ResourceDiscovery/Graph/Query/GraphQueryBuilder.cs#L143

And the tags would define in list:
 
```yaml
      tags:
        app: 
        - promitor
        - argocd
```
This one will break the current setting since it takes a list instead of a string value, we could consider to handle both cases too make it backward compatible.

I could take this work / make changes and test but before that we would love some inputs or if there was another way to achieve our goal without making these changes.
