### DISCUSSION TITLE
Promitor on Kubernetes CPU & Memory Consumption

### DISCUSSION THREAD

**Discussion by hmrc87** [tomkerkhove/promitor#1788] [Q&A]
Hi,
I am experimenting with Promitor mainly in order to monitor our Servicebus queues and topics. I am scraping a "few" of them by using the dimension EntityName,

I have 6 of these metrics defined like this
```
 - name: azure_service_bus_active_messages
    description: "Count of active messages in a Queue/Topic."
    resourceType: ServiceBusNamespace 
    azureMetricConfiguration:
      metricName: ActiveMessages
      aggregation:
        type: Average
      dimension:
        name: EntityName
    resources:
      - namespace: infra-northeurope-sbns-dev
        resourceGroupName: infra-northeurope-rg-dev
      - namespace: infra-northeurope-sbns-stage
        resourceGroupName: infra-northeurope-rg-stage
      - namespace: infra-northeurope-sbns-prod
        resourceGroupName: infra-northeurope-rg-prod
```

-> Scraping interval is set to 5min

The problem is: we see a lot of CPU and Memory usage in the Kubernetes cluster, is this expected? Why doesn't the Memory usage go down after a scraping interval? I was expecting a lot less consumption from the scraper
![image](https://user-images.githubusercontent.com/1226017/136194979-0aef445a-f573-46e9-a0c6-1aa1f374ab15.png)
