### DISCUSSION TITLE
How Prometheus gets metrics data? is it Pulled by Prometheus or Promitor pushes it?

### DISCUSSION THREAD

**Discussion by testskills** [tomkerkhove/promitor#1874] [Q&A] [answered]
Apology for basic question. But I do see 2 configurations.  Which exact configuration is responsible for getting scraped metrics data into Prometheus. 

**Prometheus**:

```yaml
  - job_name: promitor-agent-scraper
      metrics_path: /metrics
      static_configs:
        - targets:
          - promitor-agent-scraper.default.svc.cluster.local:8888
```

**Promitor-scraper**:

```yaml
metricSinks:
      prometheusScrapingEndpoint:
        metricUnavailableValue: "NaN"
        enableMetricTimestamps: "true"
        baseUriPath: "/metrics"
        labels:
          transformation: "None"
```
