### DISCUSSION TITLE
Total Metric aggregation type provides wrong metric value

### DISCUSSION THREAD

**Discussion by PowerSurj** [tomkerkhove/promitor#1917] [General] [answered]
I noticed that when I use Total metric aggregation type lookups with aggregation intervals of 4 and 5 minutes the resulting metric differs from the Azure Monitor value by multiple times.
However, I get correct metric values (within expected average range) when using aggregation interval of 3 minutes.

Average type aggregation metrics don't seem to be affected by this.

Using Scraper v2.6.0

Config example:
```
metricDefaults:
  aggregation:
    interval: 00:04:00
  scraping:
    schedule: "* * * * *"
metrics:
  - name: azure_front_door_request_count_per_http_status_group
    description: "The number of client requests served by the HTTP/S proxy per HttpStatusGroup dimension"
    resourceType: FrontDoor
    azureMetricConfiguration:
      metricName: RequestCount
      aggregation:
        type: Total
      dimension:
        name: HttpStatusGroup
    resourceDiscoveryGroups:
      - name: FrontDoor
```

Azure Monitor stats
![image](https://user-images.githubusercontent.com/52036509/149740107-4e915477-ff99-4a0e-b54e-e4ffc856309c.png)

Prometheus scraped metrics from the Scraper agent (filter for httpstatusgroup="2XX" label)
![image](https://user-images.githubusercontent.com/52036509/149741114-395ed06f-3ffd-494e-a23d-3e223829b3b6.png)

Am I missing some basic setting to get metrics right?
