### DISCUSSION TITLE
container-registry-landscape StorageUsed and AgentPoolCPUTime doesn't seem to work

### DISCUSSION THREAD

**Discussion by isantospardo** [tomkerkhove/promitor#1921] [Q&A]
Hi,
I am adding multiple metrics, but I see the following metrics do not work.
```
....
- name: azure_storage_container_registry
  description: "The amount of storage used by the container registry"
  resourceType: ContainerRegistry
  azureMetricConfiguration:
    metricName: StorageUsed
    aggregation:
      type: Average
  resourceDiscoveryGroups:
    - name: container-registry-landscape
- name: azure_agent_pool_cpu_container_registry
  description: "AgentPool CPU Time of the container registry"
  resourceType: ContainerRegistry
  azureMetricConfiguration:
    metricName: AgentPoolCPUTime
    aggregation:
      type: Total
  resourceDiscoveryGroups:
    - name: container-registry-landscape
```

```
resourceDiscoveryGroups:
  - name: container-registry-landscape
    type: ContainerRegistry
 .....
```

Is there anything wrong I am doing?
