### DISCUSSION TITLE
Metric Declaration for Application Insights "Resource Type" is not valid

### DISCUSSION THREAD

**Discussion by mgLearningAccount2** [tomkerkhove/promitor#2064] [Q&A] [answered]
### Report

I have installed docker in my local system to connect with Prometheus (application installed) locally as well without any use of kubernetes ( like AKS) to scrap data form Azure AppInsight, just to make simulate simple data scrap scenario locally.

I have configured the metric-declaration.yml file with tenantId, SubscriptionId, resourcegroup name along with the metric data as well and also configuring runtime.yml with AppInsight telemetry with instrumentation key.

I have ran the below code to window cmd prompt,
```
docker run -d -p 8999:80 --name promitor-agent-scraper --env AUTH_APPKEY=xxxxxxxxxxx-xxxx-xxxx-xxxxxxxx --volume c:/promitor/metrics-declaration.yaml:/config/metrics-declaration.yaml --volume c:/promitor/runtime.yaml:/config/runtime.yaml ghcr.io/tomkerkhove/promitor-agent-scraper:2.5.0
```
(note: AUTH_APPKEY  is seem to be valid one and [doc link](https://docs.promitor.io/v2.7/deployment/scraper/docker/?h=promitor_auth_appid) represent incorrect    )

My container is created but facing an issue stating that "resouceType" in metric-declaration.yml file is not valid. 

![image](https://user-images.githubusercontent.com/106647650/176464227-cc169a9f-5da6-41f7-a127-d83a46602c7a.png)

### Expected Behavior

The value given to the "resouceType" is valid as per the [link ](https://docs.promitor.io/v2.7/scraping/providers/application-insights/#example) from Promitor. And this initial validation output should result in success. which is the excepted Behavior.

### Actual Behavior

But Instead the resourceType: ApplicationInsights is resulting in,
Error 20:19: 'ApplicationInsights' is not a valid value for 'resourceType'.

### Steps to Reproduce the Problem

1. Install Docker into your local machine.
2. Create folder for runtime & metric-declaration.yml files.
3. Configure the file with required value from the azure app insight.
4. Run docker command,
docker run -d -p 8999:80 --name promitor-agent-scraper --env AUTH_APPKEY=xxxxxxxxxxx-xxxx-xxxx-xxxxxxxx --volume c:/promitor/metrics-declaration.yaml:/config/metrics-declaration.yaml --volume c:/promitor/runtime.yaml:/config/runtime.yaml ghcr.io/tomkerkhove/promitor-agent-scraper:2.5.0

5. once the container is created check log or navigate to the docker desktop application and click on status and select log.
...

### Component

Scraper

### Version

2.5.0

### Configuration

Configuration:

```yaml
# metric-declaration
version: v1
azureMetadata:
  tenantId:  xxxxxxxxxxx-xxxx-xxxx-xxxxxxxxxx
  subscriptionId:  xxxxxxxxxxx-xxxx-xxxx-xxxxxxxxxx
  resourceGroupName: xxxxxxxxxxx-xxxx-xxxx-xxxxxxxxxx
  cloud: Global
metricDefaults:
  aggregation:
    interval: 00:05:00
  limit: 10
  labels:
    geo: Global
    environment: dev
  scraping:
    # Every minute
    schedule: "0 * * ? * *"
metrics:
  - name: MetricChecker
    description: "Average amount of server exceptions in Azure Application Insights"
    resourceType: ApplicationInsights
    azureMetricConfiguration:
      metricName: exceptions/server
      aggregation:
        type: Average
    resources: # Optional, required when no resource discovery is configured
      - name: promitor-application-gateway-1
      - name: promitor-application-gateway-2
    resourceDiscoveryGroups: # Optional, requires Promitor Resource Discovery agent (https://promitor.io/concepts/how-it-works#using-resource-discovery)
      - name: application-insights-landscape
```

```yaml
# runtime
authentication:
  # Options are ServicePrincipal, SystemAssignedManagedIdentity, UserAssignedManagedIdentity.
  mode: ServicePrincipal # Optional. Default: ServicePrincipal.
  identityId: xxxx-xxxx-xxxx # Optional.
server:
  httpPort: 80 # Optional. Default: 80
metricSinks:
  prometheusScrapingEndpoint:
    metricUnavailableValue: NaN # Optional. Default: NaN
    enableMetricTimestamps: true # Optional. Default: true
    baseUriPath: /metrics # Optional. Default: /metrics
    labels:
      transformation: None # Optional. Default: None.
metricsConfiguration:
  absolutePath: /config/metrics-declaration.yaml # Optional. Default: /config/metrics-declaration.yaml
telemetry:
  applicationInsights:
    instrumentationKey: xxxxxxxxx-xxxx-xxxx-xxxxxxxx# Optional. Note: Required to be specified when turned on
    isEnabled: false # Optional. Default: false
    verbosity: trace # Optional. Default: N/A
  containerLogs:
    isEnabled: true # Optional. Default: true
    verbosity: trace # Optional. Default: N/A
  defaultVerbosity: error # Optional. Default: error
resourceDiscovery:
  host: promitor.agents.resourcediscovery # Optional. DNS name of Promitor Resource Discovery agent
  enabled: true # Optional. Indication whether or not resource discovery is enabled through the Promitor Resource Discovery agent.
  port: 88 # Optional. Port of Promitor Resource Discovery agent
```

### Logs

![image](https://user-images.githubusercontent.com/106647650/176468593-b24465e9-3631-45ec-99f2-8c2e00970523.png)

### Platform

Microsoft Azure
