### DISCUSSION TITLE
While scraping data for postgresql I am not getting correct data.

### DISCUSSION THREAD

**Discussion by SumeetWarankar** [tomkerkhove/promitor#2078] [Q&A]
Below is my yaml config which I am using to scrape CPU percent for postgresql.

```yaml
metrics:
- azureMetricConfiguration:
    aggregation:
      type: Average
      interval: 00:05:00
    metricName: cpu_percent
  scraping:
    schedule: "0 * * ? * *"
  description: CPU percent
  name: azure_postgresql_cpu_percent
  resourceType: PostgreSql
  resourceDiscoveryGroups:
  - name: postgre-sql`
```
  
If I use above config then I am getting null value for this metric. But if I use below config wherein I am changing aggregation type as None then I am getting 0 as value for the same metric even though this metric is having data in it.

```yaml
metrics:
- azureMetricConfiguration:
    aggregation:
      type: None
      interval: 00:05:00
    metricName: cpu_percent
  scraping:
    schedule: "0 * * ? * *"
  description: CPU percent
  name: azure_postgresql_cpu_percent
  resourceType: PostgreSql
  resourceDiscoveryGroups:
  - name: postgre-sql`
```
  
Could you please help me in resolving this issue
