### DISCUSSION TITLE
Total Metric cycling values including 0 instead of giving consistent result

### DISCUSSION THREAD

**Discussion by danielpof** [tomkerkhove/promitor#2149] [Q&A] [answered]
I have this configuration:

```yaml
    metricDefaults:
      aggregation:
        interval: 00:05:00
      scraping:
        schedule: "* * * * *"
    metrics:
      - name: azure_cosmos_db_data_usage
        description: Total data usage reported at 5 minutes granularity
        resourceType: CosmosDb
        azureMetricConfiguration:
          metricName: DataUsage
          aggregation:
            type: Total
```

But when looking at the metric i'm getting a constantly cycling set of values including zero instead of the expected slowly growing value. 
![image](https://user-images.githubusercontent.com/71904581/194532599-cd92e1c8-c22c-426d-a804-b8467f043730.png)

I've done an `az monitor metric list` command and the returned metrics are the expected values minus the last one which seems to always contain an invalid data point.

```json
{ 
  "timeseries": [
    {
      "data": [
        {
          "average": null,
          "count": null,
          "maximum": null,
          "minimum": null,
          "timeStamp": "2022-10-07T09:26:00+00:00",
          "total": 84292960256.0
        },
        {
          "average": null,
          "count": null,
          "maximum": null,
          "minimum": null,
          "timeStamp": "2022-10-07T09:31:00+00:00",
          "total": 84292960256.0
        },
        {
          "average": null,
          "count": null,
          "maximum": null,
          "minimum": null,
          "timeStamp": "2022-10-07T09:36:00+00:00",
          "total": 84293025792.0
        },
        {
          "average": null,
          "count": null,
          "maximum": null,
          "minimum": null,
          "timeStamp": "2022-10-07T09:41:00+00:00",
          "total": 84292960256.0
        },
        {
          "average": null,
          "count": null,
          "maximum": null,
          "minimum": null,
          "timeStamp": "2022-10-07T09:46:00+00:00",
          "total": 84292960256.0
        },
        {
          "average": null,
          "count": null,
          "maximum": null,
          "minimum": null,
          "timeStamp": "2022-10-07T09:51:00+00:00",
          "total": 84289912832.0
        },
        {
          "average": null,
          "count": null,
          "maximum": null,
          "minimum": null,
          "timeStamp": "2022-10-07T09:56:00+00:00",
          "total": 84290043904.0
        },
        {
          "average": null,
          "count": null,
          "maximum": null,
          "minimum": null,
          "timeStamp": "2022-10-07T10:01:00+00:00",
          "total": 84289978368.0
        },
        {
          "average": null,
          "count": null,
          "maximum": null,
          "minimum": null,
          "timeStamp": "2022-10-07T10:06:00+00:00",
          "total": 84290043904.0
        },
        {
          "average": null,
          "count": null,
          "maximum": null,
          "minimum": null,
          "timeStamp": "2022-10-07T10:11:00+00:00",
          "total": 84293681152.0
        },
        {
          "average": null,
          "count": null,
          "maximum": null,
          "minimum": null,
          "timeStamp": "2022-10-07T10:16:00+00:00",
          "total": 84297678848.0
        },
        {
          "average": null,
          "count": null,
          "maximum": null,
          "minimum": null,
          "timeStamp": "2022-10-07T10:21:00+00:00",
          "total": 11983486976.0
        }
      ],
      "metadatavalues": []
    }
  ],
  "type": "Microsoft.Insights/metrics",
  "unit": "Bytes"
}
```

I tried playing with interval to see if it would help without any effect, so not sure what I'm doing wrong, if anyone could point me in the right direction I'd appreciate it.
