### DISCUSSION TITLE
service bus queue size and max size

### DISCUSSION THREAD

**Discussion by rmacian** [tomkerkhove/promitor#2393] [General]
I need to monitor my azure service bus queues and create an alarm on alertmanager based on the percent of the queue being used.
I have my metrics splitted by entity_name but each queue has different size, so I need the metric obtained from azure monitor and a someway to have the queue size. I first thought about labels but are at a metric level and I should need it at resource level. Here is how I am configuring my scrapping configured with a jinja2 template:

```yaml
  - name: azure_servicebusnamespace_size
    description: "Size of an Queue/Topic in Bytes."
    resourceType: ServiceBusNamespace
    azureMetricConfiguration:
      metricName: Size
      aggregation:
        type: Average
    scraping:
      schedule: "*/10 * * * *"
    resources:
{% for key, value in service_bus.queues.items() %}
    - namespace: {{ service_bus.namespace }}
      queueName: {{ value.name }}
{% endfor %}
```

and the info I need for templating is in here:
```yaml
service_bus:
  namespace: myname-msg"
  policy: "myname-msg-queue-policy"
  queues:
    queue1:
      name: "first_queue"
      lock_duration_in_seconds: 60
      max_size_in_mb: 2048
    queue2:
      name: "second_queue"
      lock_duration_in_seconds: 60
      max_size_in_mb: 5120
    queue3:
      name: "third_queue"
      lock_duration_in_seconds: 60
      max_size_in_mb: 1024
```

I wish I could do something like that:

```yaml
  - name: azure_servicebusnamespace_size
    description: "Size of an Queue/Topic in Bytes."
    resourceType: ServiceBusNamespace
    azureMetricConfiguration:
      metricName: Size
      aggregation:
        type: Average
    scraping:
      schedule: "*/10 * * * *"
    resources:
{% for key, value in service_bus.queues.items() %}
    - namespace: {{ service_bus.namespace }}
      queueName: {{ value.name }}
      labels: 
        max_size: {{ value.max_size_in_mb }}
{% endfor %}
```
