### DISCUSSION TITLE
Change log level

### DISCUSSION THREAD

**Discussion by iamrubeng** [tomkerkhove/promitor#2416] [Q&A]
How can I set log level to warn?

`[13:01:01 INF] Found value 200995 for metric azure_network_public_ip_bytes with aggregation interval 00:05:00
[13:01:01 INF] Found value 27529 for metric azure_network_interface_bytes_sent with aggregation interval 00:05:00
[13:01:01 INF] Found value 230690 for metric azure_compute_virtual_machine_network_in_total with aggregation interval 00:05:00
[13:01:01 INF] Found value 379853 for metric azure_compute_virtual_machine_network_in_total with aggregation interval 00:05:00
[13:01:01 INF] Found value 1.9116666666666668 for metric azure_compute_virtual_machine_cpu_percentage with aggregation interval 00:05:00
[13:01:01 INF] Found value 2.86625 for metric azure_compute_virtual_machine_cpu_percentage with aggregation interval 00:05:00`

**Comment by tomkerkhove** [comment]
You can configure this : https://docs.promitor.io/v2.11/scraping/runtime-configuration/

**Reply by iamrubeng** [reply]
I've already configure it using:

```yaml
azureMonitor:
  logging:
    isEnabled: false # Optional. Default: false
  integration:
    history:
      startingFromInHours: 24 # Optional. Default: 12
telemetry:
  defaultVerbosity: error
```

But same..
