### DISCUSSION TITLE
Scrapping Azure Storage Queue metrics - Getting Authorization Error

### DISCUSSION THREAD

**Discussion by manojbhatt** [tomkerkhove/promitor#2443] [Q&A]
I am trying to scrap metrics for Azure queues which are in storage account which have network restriction. ( Only allowed IPs (subnets) can access the queues ). I have promitor running in a cluster of which the IP is whitelisted. 

This is the metric declaration - 

```
      - name: azure_storage_queue_message_count
        description: "The number of messages on Azure storage queue"
        resourceType: StorageQueue
        azureMetricConfiguration:
          metricName: MessageCount
          aggregation:
            type: Total
        resources:
          - accountName: testStorageAccount
            queueName: test-queue
            sasToken:
              environmentVariable: "AZURE_STORAGE_QUEUE_SAS_TOKEN"
```

In the promitor logs I'm seeing following error - 

`13:15:00 FTL] Failed to scrape resource for metric 'azure_storage_queue_message_count'Microsoft.Azure.Storage.StorageException: This request is not authorized to perform this operation using this resource type.   at Microsoft.Azure.Storage.Core.Executor.Executor.ExecuteAsync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token)   at Promitor.Integrations.AzureStorage.AzureStorageQueueClient.GetQueueReference(String accountName, String queueName, String sasToken) in /src/Promitor.Integrations.AzureStorage/AzureStorageQueueClient.cs:line 68   at Promitor.Integrations.AzureStorage.AzureStorageQueueClient.GetQueueMessageCountAsync(String accountName, String queueName, String sasToken) in /src/Promitor.Integrations.AzureStorage/AzureStorageQueueClient.cs:line 31   at Promitor.Core.Scraping.ResourceTypes.StorageQueueScraper.ScrapeResourceAsync(String subscriptionId, ScrapeDefinition`1 scrapeDefinition, StorageQueueResourceDefinition resource, AggregationType aggregationType, TimeSpan aggregationInterval) in /src/Promitor.Core.Scraping/StorageQueueScraper.cs:line 41   at Promitor.Core.Scraping.Scraper`1.ScrapeAsync(ScrapeDefinition`1 scrapeDefinition) in /src/Promitor.Core.Scraping/Scraper.cs:line 104Request InformationRequestID:6c3d8700-3003-0069-30da-601ee4000000RequestDate:Fri, 16 Feb 2024 13:15:00 GMTStatusMessage:This request is not authorized to perform this operation using this resource type.ErrorCode:AuthorizationResourceTypeMismatch`

Can anyone please help me understanding what I'm doing wrong here ? I'm able to get the metrics for other resourceTypes.
