### DISCUSSION TITLE
Scraping Azure Data Factory Integration Runtime Metrics

### DISCUSSION THREAD

**Discussion by nc-pnan** [tomkerkhove/promitor#2539] [General]
Hi,
I am attempting to scrape integration runtime metrics from Data Factory in Azure. I can successfully scrape other metrics from data factory like pipeline failures. From the logs it appears I have to use the dimension key in my metric configuration to set the integration runtime name. I have tried several different ways of configurating this, but I keep getting variations of the same error and no metrics. I cant find much if any documentation on how to configure this, except for a small bit on configuring dimension which did not help much. I hope someone knows how this is supposed to be configured and can help me out.

This is the error I am getting:
`BadRequest: Metric: IntegrationRuntimeCpuPercentage does not support requested dimension combination: name, supported ones are: IntegrationRuntimeName,NodeName,
`

Here is my metric configuration and discovery group:
```
metrics:
 - name: promitor_azure_data_factory_integration_runtime_available_cpu
      description: "The CPU usage (%) of ADF integration runtime"
      resourceType: DataFactory
      azureMetricConfiguration:
        metricName: IntegrationRuntimeCpuPercentage
        dimension:
          IntegrationRuntimeName: "datafactory-self-hosted-ir-name"
        aggregation:
          type: Average
          interval: 00:01:00
      resourceDiscoveryGroups:  
      - name: data-factory-landscape
```
```
  resourceDiscoveryGroups:
  - name: data-factory-landscape
    type: DataFactory
```
