### DISCUSSION TITLE
Override environment variable when using a list

### DISCUSSION THREAD

**Discussion by bentonjimmy** [tomkerkhove/promitor#2577] [Q&A]
I'm trying to create an override environment variable so that I can use an environment variable to set the resource namespace of a metric.  Below is the snippet of yaml that I'm attempting to override.  I'd like to replace the namespace value of `value-to-be-overrided` with the value from an environment variable.  I tried `name: PROMITOR_YAML_OVERRIDE_metrics__0__resources__0__namespace` which didn't override the value.

```
metrics:
  - name: ogma_deadlettered_queue_size
    description: "Amount of deadlettered messages of the 'ogma' queue"
    resourceType: ServiceBusNamespace
    azureMetricConfiguration:
      metricName: DeadletteredMessages
      aggregation:
        type: Total
    resources:
      - namespace: value-to-be-overrided
        queueName: ogma
```

Is it possible to use the environment variables this way?  What is doing the overriding of the yaml values?
