### ISSUE TITLE
Metric with multiple resources defined only reporting last defined resource rather than all

### ISSUE THREAD

**Issue by davidharcourt** [tomkerkhove/promitor#1065]
When creating a metric scraper with multiple defined resources, Promitor only returns the metric for the last listed resource rather than all in the list.

## Expected Behavior
Promitor should return the stated metric for all declared resources

## Actual Behavior
Promitor returns the stated metric for only the last declared resource

## Steps to Reproduce the Problem

  1. Run a Promitor container with a metrics-declaration.yaml with multiple resources declared for the metric to be scraped. 
  2. Check the output of the scraper on the Prometheus (legacy) scrape endpoint

## Configuration
Provide insights in the configuration that you are using:
- Configured scraping schedule: 
`schedule: "0 * * ? * *"`
<details>
<summary>Used scraping configuration</summary>

```yaml
version: v1
azureMetadata:
  tenantId: 
  subscriptionId: 
  resourceGroupName: 
metricDefaults:
  aggregation:
    interval: 00:01:00
  scraping:
    # Every minute
    schedule: "0 * * ? * *"
metrics:
  - name: azure_storage_account_usage
    description: "Storage account metrics"
    resourceType: StorageAccount
    labels:
      app: promitor
      tier: storage
      subtier: storageaccount
    scraping:
      # Every minute
      schedule: "0 * * ? * *"
    azureMetricConfiguration:
      metricName: UsedCapacity
      aggregation:
        type: Average
    resources:
      - accountName: 'firststorageaccount'
        resourceGroupName: 'firststorageaccount-rg'
        subscriptionId: 'subscriptionid'
      - accountName: 'secondstorageaccount'
        resourceGroupName: 'secondstorageaccount-rg'
        subscriptionId: 'subscriptionid'
      - accountName: 'thirdstorageaccount'
        resourceGroupName: 'thirdstorageaccount-rg'
        subscriptionId: 'subscriptionid'
      - accountName: 'fourthstorageaccount'
        resourceGroupName: 'fourthstorageaccount-rg'
        subscriptionId: 'subscriptionid'
      - accountName: 'fifthstorageaccount'
        resourceGroupName: 'fifthstorageaccount-rg'
        subscriptionId: 'subscriptionid`
```
  
</details>

## Specifications

  - Version: 1.6.0 (image tag)
  - Platform: Kubernetes (Deployment configured with Kustomize and without Helm)
  - Subsystem:
