### ISSUE TITLE
Scraper Azure Automation

### ISSUE THREAD

**Issue by jeff-coding-for-fun** [tomkerkhove/promitor#1460]
Hi,
Thank you to develop an awesome scraper for monitoring!

I need to monitor the ressource "Azure Automation" but the scraper does not exist for the moment with promitor.
The metric is here : https://docs.microsoft.com/en-us/azure/azure-monitor/platform/metrics-supported#microsoftautomationautomationaccounts

Actually we use an other scraper https://github.com/RobustPerception/azure_metrics_exporter
```yaml
resource_tags:
   - resource_tag_name: "MONITORING"
     resource_tag_value: "ENABLE"
     resource_types:
       - "Microsoft.Automation/automationAccounts"
     metrics:
       - name: "TotalJob"
```

Is it possible to implement this new feature for the further version of your product ?
I will be awesome !

Thank you very much
