### ISSUE TITLE
Deprecation Notice - Service Principle identity is moved to runtime configuration

### ISSUE THREAD

**Issue by tomkerkhove** [tomkerkhove/promitor#1582]
Promitor has been using service principle authentication from its inception where the identity inforation was configured through the following environment variables:

- `PROMITOR_AUTH_APPKEY`
- `PROMITOR_AUTH_APPID`

However, as of Promitor Scraper v2.2.0 & Resource Discovery v0.3.0, users can choose how agents authenticate to Microsoft
 Azure by declaring the authentication mode in the server configuration:

```yaml
authentication:
  # Options are ServicePrincipal, SystemAssigedManagedIdentity, UserAssigedManagedIdentity.
  mode: ServicePrincipal
  identityId: xxxx-xxxx-xxxx
```

With this new approach, users can use Managed Identity authentication leveraging no-secret authentication or keep on
 using Service Principle authentication.

**Deprecated as of:**
Promitor Scraper v2.2.0 & Promitor Resource Discovery v0.3.0

**Will be removed on:**
Promitor Scraper v3.0 & Promitor Resource Discovery v1.0

**Impact:**
Migration is required - Use the [authentication configuration](https://promitor.io/configuration/v2.x/azure-authentication#supported-authentication-mechanisms)
 to specify Service Principle authentication and configure the identity id in the server configuration.

**How to migrate:**

1. Configure service principle authentication in server configuration:

```yaml
authentication:
  mode: ServicePrincipal
  identityId: xxxx-xxxx-xxxx
```

2. Remove `PROMITOR_AUTH_APPID` environment variable

**Alternative:**
None.
