### ISSUE TITLE
Label values are not sanitized properly sometimes

### ISSUE THREAD

**Issue by DaveOHenry** [tomkerkhove/promitor#1596]
### Report

Sometimes the case of metric labels change from one scrape to the next one. Unfortunately it's not deterministic which case the Azure metrics api returns. Promitor already tries to lower-case the names, but it looks like it doesn't work in all cases.

We have some backend pools in Azure Application Gateway. The metric dimension names are auto-generated somehow and look like this (```<name of backend pool>~<name of http settings```):
```
appGWBackendPool-app-dev~backendHttpSettings-app-dev
```

The names directly from the Azure api look like this:
```
appgwbackendpool-app-dev~backendhttpsettings-app-dev
or "sometimes" ...
appGWBackendPool-app-dev~backendHttpSettings-app-dev
```

Promitor shows mostly lower-case names, but sometimes:
```
appgwbackendpool-app-dev~backendHttpSettings-app-dev
```

Therefore I guess that the ```~``` character breaks the sanitizing function somehow.

FWIW: I have also seen different Azure apis return different cases for resource group names. Maybe it's a good idea ```.ToLower()``` every label value that depends on data from Azure.

### Expected Behavior

Label values are always lower case.

### Actual Behavior

Case of label values is not deterministic.

### Steps to Reproduce the Problem

Can't really reproduce the issue. It happens from time to time.

### Component

Scraper

### Version

Helm chart 2.2.1

### Configuration

Configuration:

```yaml
metrics:
  - name: azure_application_gateway_total_time_ms
    description: "Average total time in milliseconds of Azure Application Gateway"
    resourceType: ApplicationGateway
    azureMetricConfiguration:
      metricName: ApplicationGatewayTotalTime
      aggregation:
        type: Average
      dimension:
        name: Listener
    resourceDiscoveryGroups:
    - name: appgw-landscape
  - name: azure_application_gateway_backend_first_byte_response_time_ms
    description: "Time between start of a connection to the backend and receiving the first byte of the response header, approximating backend processing time"
    resourceType: ApplicationGateway
    azureMetricConfiguration:
      metricName: BackendFirstByteResponseTime
      aggregation:
        type: Average
      dimension:
        name: BackendPool
    resourceDiscoveryGroups:
    - name: appgw-landscape
  - name: azure_application_gateway_response_status
    description: "Http response status of Azure Application Gateway"
    resourceType: ApplicationGateway
    azureMetricConfiguration:
      metricName: ResponseStatus
      aggregation:
        type: Total
      dimension:
        name: HttpStatusGroup
    resourceDiscoveryGroups:
    - name: appgw-landscape
  - name: azure_application_gateway_backend_response_status
    description: "Http response status of Azure Application Gateway backend pools"
    resourceType: ApplicationGateway
    azureMetricConfiguration:
      metricName: BackendResponseStatus
      aggregation:
        type: Total
      dimension:
        name: HttpStatusGroup
    resourceDiscoveryGroups:
    - name: appgw-landscape
  - name: azure_application_gateway_current_connections
    description: "Count of current connections on Azure Application Gateway"
    resourceType: ApplicationGateway
    azureMetricConfiguration:
      metricName: CurrentConnections
      aggregation:
        type: Total
    resourceDiscoveryGroups:
    - name: appgw-landscape
  - name: azure_application_gateway_total_requests
    description: "Count of total requests on Azure Application Gateway"
    resourceType: ApplicationGateway
    azureMetricConfiguration:
      metricName: TotalRequests
      aggregation:
        type: Total
      dimension:
        name: BackendSettingsPool
    resourceDiscoveryGroups:
    - name: appgw-landscape
  - name: azure_application_gateway_failed_requests
    description: "Count of failed requests on Azure Application Gateway"
    resourceType: ApplicationGateway
    azureMetricConfiguration:
      metricName: FailedRequests
      aggregation:
        type: Total
      dimension:
        name: BackendSettingsPool
    resourceDiscoveryGroups:
    - name: appgw-landscape
  - name: azure_application_gateway_compute_units
    description: "Compute Units consumed by Application Gateway"
    resourceType: ApplicationGateway
    azureMetricConfiguration:
      metricName: ComputeUnits
      aggregation:
        type: Average
    resourceDiscoveryGroups:
    - name: appgw-landscape
  - name: azure_application_gateway_capacity_units
    description: "Capacity Units consumed by Application Gateway"
    resourceType: ApplicationGateway
    azureMetricConfiguration:
      metricName: CapacityUnits
      aggregation:
        type: Average
    resourceDiscoveryGroups:
    - name: appgw-landscape
```

### Platform

Microsoft Azure
