### ISSUE TITLE
Provide capability to use multiple metric dimensions

### ISSUE THREAD

**Issue by tomkerkhove** [tomkerkhove/promitor#1820]
### Proposal

Provide capability to use multiple metric dimensions instead of just one.

Our current metric declaration looks as following:
```yaml
- name: azure_service_bus_active_messages
    description: "The number of active messages on a service bus queue."
    resourceType: ServiceBusNamespace
    labels:
      app: promitor
      tier: messaging
    scraping:
      # Every 2 minutes
      schedule: "0 */2 * ? * *"
    azureMetricConfiguration:
      metricName: ActiveMessages
      limit: 5
      dimension:
        name: <dimension-name>
      aggregation:
        type: Total
        interval: 00:15:00
    resources: # Optional, required when no resource discovery is configured
      - namespace: promitor-messaging
        queueName: orders
```

This will change to:
```diff
- name: azure_service_bus_active_messages
    description: "The number of active messages on a service bus queue."
    resourceType: ServiceBusNamespace
    labels:
      app: promitor
      tier: messaging
    scraping:
      # Every 2 minutes
      schedule: "0 */2 * ? * *"
    azureMetricConfiguration:
      metricName: ActiveMessages
      limit: 5
      dimension: # Deprecated, use dimensions instead
        name: <dimension-name>
+     dimensions:
+     - name: <dimension-name-1>
+     - name: <dimension-name-2>
      aggregation:
        type: Total
        interval: 00:15:00
    resources: # Optional, required when no resource discovery is configured
      - namespace: promitor-messaging
        queueName: orders
```

Relates to #809

### Component

Scraper

**Comment by ronyrv13** [comment]
Hello @tomkerkhove ,
On which scraper version we can expect this?..
I am using 2.6.1 promitor scraper, but when i used above config i got below error-

Warning 25:5: Unknown field 'dimensions'. Did you mean 'dimension'?
Warning 37:5: Unknown field 'dimensions'. Did you mean 'dimension'?
[12:13:52 WRN] No metric information found for metric Data Disk Read Operations/Sec with dimension null. Details: No time series was found
[12:13:52 WRN] No metric information found for metric Data Disk Write Operations/Sec with dimension null. Details: No time series was found

My azureMetricConfiguration - 
```yaml
- name: azure_virtual_machine_scalesets_disk_read_op
  description: "Average Disk Read Operations Per seconds"
  resourceType: VirtualMachineScaleSet
  azureMetricConfiguration:
    metricName: Data Disk Read Operations/Sec
    dimensions:
    - name: LUN
    - name: VMName
    aggregation:
      type: Average
  resourceDiscoveryGroups:
  - name: azure-rony-use2-resources
```
