### ISSUE TITLE
Discovery with multiple tags only require one match

### ISSUE THREAD

**Issue by tomkerkhove** [tomkerkhove/promitor#1827]
### Report

Discovery with multiple tags only require one match instead of all of them which does not allow you to define more granular tag filters.

### Expected Behavior

Act as an AND

### Actual Behavior

Acts as an OR

### Steps to Reproduce the Problem

1. Create group as mentioned below
2. Query for resources
3. All resources that have at least one tag match are returned, not when all 3 are present
...

### Component

Resource Discovery

### Version

0.5.0

### Configuration

Configuration:

```yaml
- name: one-instance-tag-with-multi-value-scenario
  type: LogicApp
  criteria:
    include:
      tags:
        app: promitor-resource-discovery-tests
        region: europe
        instance: promitor-testing-resource-eu-workflow-eu-[0-9]
```

### Logs

N/A
