### ISSUE TITLE
environment variables in runtime.yaml

### ISSUE THREAD

**Issue by PowerSurj** [tomkerkhove/promitor#1830]
### Proposal

Make environment variables resolvable in runtime.yaml
Currently only literal values are supported. Environment variables would facilitate secrets passing through CSI.

I tested this in promitor-agent-resource-discovery 0.6.0 image deployed through helm chart
I define environment variable through CSI and reference it in runtime.yaml through values.yaml

```
azureAuthentication:
  mode: UserAssignedManagedIdentity
  identity:
    id: ${PR_AZURE_MANAGED_IDENTITY_CLIENT_ID}
    binding: promitor-pod-identity
```
In this example i reference clientID 
This results in exception:

`System.AggregateException: One or more errors occurred. (ManagedIdentityCredential authentication failed: 'no azure identity found for request clientID ${PR##### REDACTED #####_ID}
' is an invalid JSON literal. Expected the literal 'null'. LineNumber: 0 | BytePositionInLine: 1.`

### Component

Resource Discovery
