### ISSUE TITLE
Provide documentation on using subscription ID overrides on a per-metric basics

### ISSUE THREAD

**Issue by ahurtaud** [tomkerkhove/promitor#1849]
### Proposal

As of today, because I use 1 instance of scraper managing multiple subscriptions (using resource discovery). I have set dummy AzureMetadata:
```yaml
azureMetadata:
  tenantId: "xxxx-xxxx-xxxxxxxxxx"
  subscriptionId: "global"
  resourceGroupName: global
  cloud: "Global"
```

Because of that, it seems I am not able to use the generic azure resources because it gets subscriptionsID and resource group from this "global" azure metadata:
![Screen Shot 2021-11-24 at 17 12 07](https://user-images.githubusercontent.com/25080995/143274530-ee09c44d-9290-4757-ab72-de4de4789f16.png)

**Feature request:**
I would like the ability, in the generic metrics definition, to override the subscription and the RG name, for example like:
```yaml
resources:
# Will scrape subscriptions/<sub>/resourceGroups/<rg>/providers/Microsoft.ServiceBus/namespaces/promitor-messaging
# Where 'sub' & 'rg' are coming from azureMetadata
- resourceUri: Microsoft.ServiceBus/namespaces/promitor-messaging
  filter: EntityName eq 'orders'
  subscriptionOverride: 11111-11111-1111111111
  resourceGroupNameOverride: aaaaa
- resourceUri: Microsoft.ServiceBus/namespaces/promitor-messaging
  filter: EntityName eq 'items'
  subscriptionOverride: 22222-222222-22222222
  resourceGroupNameOverride: bbbbbbb
```

### Component

Scraper

### Contact Details

alban.hurtaud@amadeus.com

**Comment by tomkerkhove** [comment]
Fair request and I've always been reluctant to go cross-subscription but it's a fair ask!

**Comment by ahurtaud** [comment]
Actually after private discussions, this is already possible, just not documented in the https://docs.promitor.io/configuration/v2.x/metrics/generic-azure-resource

Example of implementation, tested and verified:
```yaml
  - azureMetricConfiguration:
      aggregation:
        type: Average
      metricName: cpu_percent
    description: CPU percent
    name: azure_mariadb_cpu_percent
    resourceType: Generic
    resources:
    - resourceUri: Microsoft.DBforMariaDB/servers/my-mariadb
      resourceGroupName: my-resource-group
      subscriptionId: xxxxxxx-xxxx-xxxx-xxxxx-xxxxxxxxxx
```
