### ISSUE TITLE
Total Metric aggregation type provides wrong metric value using different aggregation intervals

### ISSUE THREAD

**Issue by PowerSurj** [tomkerkhove/promitor#1935]
### Discussed in https://github.com/tomkerkhove/promitor/discussions/1917

I noticed that when I use Total metric aggregation type lookups with aggregation intervals of 4, 5 and 6 minutes the resulting metric differs from the Azure Monitor value by multiple times.
However, I get correct metric values (within expected average range) when using aggregation interval of 3 minutes.

Average type aggregation metrics don't seem to be affected by this.

You can reproduce this problem by using this subset of helm chart values

DISCOVERY
https://github.com/promitor/charts/blob/main/promitor-agent-resource-discovery/values.yaml
```
image:
  tag: "0.7.0"

resourceDiscoveryGroups:
  - name: FrontDoor
    type: FrontDoor
      criteria:
        include:
          tags:
            BusinessUnit: myunit
          regions:
            - uksouth

```

SCRAPER
https://github.com/promitor/charts/blob/main/promitor-agent-scraper/values.yaml
```
image:
  tag: "2.6.0"

metricDefaults:
  aggregation:
    interval: 00:05:00
  scraping:
    schedule: "* * * * *"
metrics:
  - name: azure_front_door_request_count_per_http_status_group
    description: "The number of client requests served by the HTTP/S proxy per HttpStatusGroup dimension"
    resourceType: FrontDoor
    azureMetricConfiguration:
      metricName: RequestCount
      aggregation:
        type: Total
      dimension:
        name: HttpStatusGroup
    resourceDiscoveryGroups:
      - name: FrontDoor

```

Azure Monitor stats
![image](https://user-images.githubusercontent.com/52036509/149740107-4e915477-ff99-4a0e-b54e-e4ffc856309c.png)

Prometheus scraped metrics from the Scraper agent (filter for httpstatusgroup="2XX" label)
![image](https://user-images.githubusercontent.com/52036509/149741114-395ed06f-3ffd-494e-a23d-3e223829b3b6.png)
