### ISSUE TITLE
Support for specifying sub/server type in resource discovery

### ISSUE THREAD

**Issue by MattiasAng** [tomkerkhove/promitor#2044]
### Proposal

I implemented the MySQL resource type a while ago, and while not a huge issue it is a bit annoying to see:
`The metric 'cpu_credits_remaining' was not found`.

The reason for these errors is that metrics available differs from MySQL Single and Flexible servers. The same is true for PostgreSQL as well. 

Currently there is no way, as far as I know, to filter resource discovery group on a server type / sub type of a resource type. This would be nice to have for these use cases, and probably others.

I might have time to implement this myself, but would like some implementation direction in that case. 

Possible declerations, depending on implementation.

Filter in resource discovery:
```yaml
version: v1
azureLandscape:
  tenantId: 00000000-0000-0000-0000-000000000000
  subscriptions:
    - 00000000-0000-0000-0000-000000000000
  cloud: Global
resourceDiscoveryGroups:
  - name: azure_mysql_single
    type: MySql
    subType: Single
  - name: azure_mysql_single
    type: MySql
    subType: Flexible
```

Filter in metric decleration:
```yaml
  - name: azure_mysql_cpu_credits_remaining
    description: "CPU credits remaining"
    resourceType: MySql
    azureMetricConfiguration:
      metricName: cpu_credits_remaining
      aggregation:
        type: Average
        interval: 00:15:00
    resourceDiscoveryGroups:
      - name: azure_mysql
         subType: Flexible
```

### Component

Resource Discovery
