### ISSUE TITLE
BadRequest while querying ServiceBusNamespace 'ActiveConnections'

### ISSUE THREAD

**Issue by gk-mevers** [tomkerkhove/promitor#2131]
### Report

When querying the metric ActiveConnections for Azure Service Bus namespaces, the scraper seems to add the dimension `entityname` automatically, which does not exist for the metric. This causes the query to fail. As you can see, that dimension is not included in the scraper configuration.

### Expected Behavior

The scraper should not add the dimension if it is not specified so the query succeeds.

### Actual Behavior

The metric query fails with a BadRequest error in the logs and the data is not retrieved from Azure Monitor.

### Steps to Reproduce the Problem

1. Add ServiceBusNamespace type to resource discovery configuration.
2. Add the query mentioned under `Configuration` to the scraper configuration.
3. Check the logs and verify that the error is present.
...

### Component

Scraper

### Version

2.6.0

### Configuration

Metric Configuration:

```yaml
      - name: azure_service_bus_active_connections_count
        description: "Current connections count on Service Bus"
        resourceType: ServiceBusNamespace
        azureMetricConfiguration:
          metricName: ActiveConnections
          aggregation:
            type: Total
            interval: 00:01:00
        resourceDiscoveryGroups:
          - name: service-bus-namespaces
```

Resource Discovery Configuration:

```yaml
    resourceDiscoveryGroups:
    - name: service-bus-namespaces
      type: ServiceBusNamespace
```

### Logs

```shell
[09:16:03 FTL] BadRequest: Metric: ActiveConnections does not support requested dimension combination: entityname, supported ones are: , TraceId: {e880f033-26b4-4401-abd5-4408dcc0c0ba}
```

### Platform

Microsoft Azure
