### ISSUE TITLE
Provide the ability to filter resources from Resource Discovery based on subscriptionId and resourceGroup

### ISSUE THREAD

**Issue by dks0296586** [tomkerkhove/promitor#2150]
### Proposal

Provide the ability for Resource Discovery to filter the resources of a given type by subscriptionId and resourceGroup.

The idea would be to have a single resourceDiscoveryGroup(ie postgres-database-landscape) that can return all the resources of that type from all subscriptions where it has Azure permissions.  The scraper would then be able to pass in optional parameters for subscriptionId/resourceGroup to the discovery API and get a response of only those resources.

For Promitor deployments that scrape a large number of targets across multiple subscriptions, this would allow reuse of a base configuration(ie Kubernetes kustomizations) across multiple scraper deployments.

Resource Discovery config example:
```
    - name: postgres-database-landscape
      type: PostgreSql  
```

Scraper metric declaration config example:
```
   metricDefaults:   
      aggregation:   
        interval: 00:05:00   
      scraping:   
        schedule: "*/2 * * * *"   
      resourceDiscoveryGroups:    
      - name:    
         subscriptionId: 'xxxxxxxx'   
         resourceGroup:   
         - rg-1   
         - rg-2   
```
....

```
   metrics:
   - name: azure_postgresql_cpu_percent_maximum  
     description: "CPU percent"  
     resourceType: PostgreSql  
     azureMetricConfiguration:  
       metricName: cpu_percent  
       aggregation:  
         type: Maximum  
     resourceDiscoveryGroups:  
     - name: postgres-database-landscape  
       subscriptionId: 'xxxxxxxx'  
       resourceGroup:  
       - rg-1  
       - rg-2
```

### Component

Resource Discovery, Scraper

### Contact Details

benjamin.lawson@dcsg.com
