### ISSUE TITLE
Total Metric cycling values including 0 instead of giving consistent result

### ISSUE THREAD

**Issue by daniel-anova** [tomkerkhove/promitor#2154]
### Report

As reported in https://github.com/tomkerkhove/promitor/discussions/2149 when importing certain metrics like `azure_cosmos_db_data_usage` the values continuously cycle from real value to 0.

### Expected Behavior

The value should be consistently showing the highest value on every point.

### Actual Behavior

Value will cycle from 0 to real value.

### Steps to Reproduce the Problem

1.
2.
3.
...

### Component

Resource Discovery, Scraper

### Version

promitor-resource-discovery: 0.8.1 (helm release), 0.8.0 (container) promitor-scraper: 2.9.0 (helm release), 2.8.0 (container)

### Configuration

Configuration:

```yaml
    metricDefaults:
      aggregation:
        interval: 00:05:00
      scraping:
        schedule: "* * * * *"
    metrics:
      - name: azure_cosmos_db_data_usage
        description: Total data usage reported at 5 minutes granularity
        resourceType: CosmosDb
        azureMetricConfiguration:
          metricName: DataUsage
          aggregation:
            type: Total
```

### Platform

Microsoft Azure

### Contact Details

daniel.ferreira@anova.com
