### ISSUE TITLE
Provide a label resourceDiscoveryGroups in metrics

### ISSUE THREAD

**Issue by romainmeunier** [tomkerkhove/promitor#2173]
### Proposal

Example metric configuration 

```yaml
     metrics:
        - name: azure_aks_kube_node_status_condition
          description: "Statuses for various node conditions"
          resourceType: KubernetesService
          azureMetricConfiguration:
            metricName: kube_node_status_condition
            dimension:
              name: condition
            aggregation:
              type: Average
          resourceDiscoveryGroups:
            - name:  foo
            - name: bar
      
```

Prometheus metric :

azure_aks_kube_node_status_condition{
   condition="ContainerRuntimeProblem",
   container="promitor-agent-scraper", endpoint="http", 
   job="promitor-agent-scraper", 
   namespace="xxx", 
   pod="promitor-agent-scraper-587fd7b4b8-562b9", 
   resource_group="k8saas-sf-tools-c2-sandbox", resource_uri="subscriptions/zzz/yyy/xxxx",
   service="promitor-agent-scraper", 
   subscription_id="xxxxxx-yyyy-yyy-1111-xxxxxx", 
   tenant_id="xxxxxx-yyyy-yyy-1111-xxxxxx",
  **resourceDiscoveryGroups="foo"**
}

### Component

Scraper

### Contact Details

romain.meunier.c@thalesdigital.io
