### ISSUE TITLE
Provide capability to configure the metric aggregation interval per metric

### ISSUE THREAD

**Issue by tomkerkhove** [tomkerkhove/promitor#256]
Metrics do not always need to be scraped with the same metrics aggregation.

We should provide the capability to configure the metric aggregation interval per metric.

### Checklist
In order to achieve this we will:
- [x] Introduce `aggregation` as part of `azureMetricConfiguration` which contains all aggregation related information
- [x] Configure the aggregation interval via `azureMetricConfiguration.aggregation.interval`
- [x] Move aggregation type ot the aggregation interval via `azureMetricConfiguration.aggregation.type`
- [x] Use configured aggregation period when scraping Azure Monitor
- [x] Update documentation on how to configure this and the impact of the size
- [x] Provide clear guidance on breaking change in documentation (depends on #255)

### What needs to be defined
- [x] How we will configure our aggragation interval - Do we stick with cron or do we use a different approach?
- [x] Do we enforce intervals higher than 5 minutes and validate it at startup, or is it the responsibility of the consumer (assuming we make this clear in docs)

### Metrics Specification

```yaml
azureMetadata:
  tenantId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
  subscriptionId: yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy
  resourceGroupName: promitor
metrics: 
  - name: demo_queue_size
    description: "Amount of active messages of the 'myqueue' queue"
    resourceType: ServiceBusQueue
    namespace: promitor-messaging
    queueName: orders
    azureMetricConfiguration:
      metricName: ActiveMessages
      aggregation:
        type: Total
        interval: <interval>
```

### Other
Closes #60 and #198
