### ISSUE TITLE
Provide capability to configure a default metric aggregation interval

### ISSUE THREAD

**Issue by tomkerkhove** [tomkerkhove/promitor#257]
Provide capability to configure a default metric aggregation interval.

This will be done when it is not configured on the metric-level. Depends on #256.

### Checklist
In order to achieve this we will:
- [x] Provide capability to configure this in the metrics declaration
- [x] Use this value for scraping if nothing is configured
- [x] Update configuration
- [x] Update documentation on how to configure this and the impact of the size

### Metrics Specification

```yaml
azureMetadata:
  tenantId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
  subscriptionId: yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy
  resourceGroupName: promitor
metricDefaults:
  aggregation:
    interval: <interval>
metrics: 
  - name: demo_queue_size
    description: "Amount of active messages of the 'myqueue' queue"
    resourceType: ServiceBusQueue
    namespace: promitor-messaging
    queueName: orders
    azureMetricConfiguration:
      metricName: ActiveMessages
      aggregation:
        type: Total
```
