### ISSUE TITLE
Provide capability to configure the scraping interval per metric

### ISSUE THREAD

**Issue by tomkerkhove** [tomkerkhove/promitor#258]
Metrics do not always need to be scraped with the same frequency.

We should provide the capability to configure the scraping interval per metric.

Once this is implemented every metric that is being scraped should be fully isolated from each other. That means if we scrap A, B & C and B fails, A & C should still be tracked.

### Checklist
In order to achieve this we will:
- [x] Configure the scraping interval via `scraping.interval`
- [ ] Use configured scraping interval per metric
- [ ] Update documentation on how to configure this

### Metrics Specification

```yaml
azureMetadata:
  tenantId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
  subscriptionId: yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy
  resourceGroupName: promitor
metrics: 
  - name: demo_queue_size
    description: "Amount of active messages of the 'myqueue' queue"
    resourceType: ServiceBusQueue
    namespace: promitor-messaging
    queueName: orders
    scraping:
      interval: <interval>
```

### Other
Closes #60 and #198
