### ISSUE TITLE
Move default scraping interval to metrics configuration

### ISSUE THREAD

**Issue by tomkerkhove** [tomkerkhove/promitor#259]
Currently, we configure the scraping interval via the `` environment variable. This approach is deprecated and moved to scraping configuration.

With #258 this can be configured per metric and should be used over this value.

### Checklist
In order to achieve this we will:
- [ ] Update documentation on how to configure this
- [ ] Provide clear guidance on breaking change in documentation (depends on #255)

### Metrics Specification

```yaml
azureMetadata:
  tenantId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
  subscriptionId: yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy
  resourceGroupName: promitor
metricDefaults:
  scraping:
    interval: <interval>
metrics: 
  - name: demo_queue_size
    description: "Amount of active messages of the 'myqueue' queue"
    resourceType: ServiceBusQueue
    namespace: promitor-messaging
    queueName: orders
    azureMetricConfiguration:
      metricName: ActiveMessages
      aggregation:
        type: Total
```
