### ISSUE TITLE
Provide integration with Azure Monitor

### ISSUE THREAD

**Issue by tomkerkhove** [tomkerkhove/promitor#4]
Provide integration with Azure Monitor where it will automatically query the Azure Monitor REST API for a set of metrics and expose them via the scrape endpoint.

Depends on #3.

### Specifications

- [x] Integrate with the Azure Monitor REST API
- [x] Provide a way to configure one or more metrics to query
- [x] Provide a way to configure how often you should pull latest representation of a metric
- [x] Provide documentation on how to configure the metrics
- [x] Provide documentation on how often you should pull latest representation of a metric
- [x] Provide documentation on how to configure the authentication with Azure Monitor

### Configuration
Metrics to scrape:
```yaml
metrics:
- metric:
  name: "my-name"
  resource-type: "Microsoft.ServiceBus"
- metric:
  name: "my-name"
  resource-type: "Microsoft.WebApps"
```

Scrape frequency:
- `PROMITOR_SCRAPE_SCHEDULE`

Azure authentication:
- `PROMITOR_AUTH_APPID`
- `PROMITOR_AUTH_APPKEY`

**Comment by tomkerkhove** [comment]
Current proposal for configuration:
```
azureConfiguration: 
  resourceGroupName: foo
  subscriptionId: bar
metrics: 
    # v1.0
  - name: "queue-size"
    description: "Size of the 'myqueue' queue"
    namespace: "myNamespace"
    queueName: "myqueue"
    resourceType: ServiceBusQueue
    # Supported in later version - This will compose the following URL to query (subscriptions/abc/resourceGroups/xyz/providers/Microsoft.ServiceBus/namespaces/monitor-integration)
  - name: "queue-size-generic" # Metric without description
    resourceType: Generic
    resourceProvider: "Microsoft.ServiceBus"
    resourceSuffix: "namespaces/monitor-integration" # Provide better name for this
    filterExpression: "EntityName eq 'myqueue'"
    resourceGroupName: xyz # Overrides default Azure configuration
    subscriptionId: abc    # Overrides default Azure configuration
```

**Comment by tomkerkhove** [comment]
This is currently what you need to query for Azure Service Bus:
```yaml
azureMetadata:
  tenantId: tenant-x
  subscriptionId: foo
  resourceGroupName: bar
metrics: 
    # v1.0
  - name: demo_queue_size
    description: "Size of the 'myqueue' queue"
    namespace: myNamespace
    azureMetricName: ActiveMessages
    azureMetricAggregation: Average
    queueName: myqueue
    resourceType: ServiceBusQueue
```

However, I don't like the names for `azureMetricName` & `azureMetricAggregation` so will need to come up with a better name

**Comment by tomkerkhove** [comment]
Change the structure to the following approach:
```yaml
azureMetadata:
  tenantId: tenant-x
  subscriptionId: foo
  resourceGroupName: bar
metrics: 
    # v1.0
  - name: demo_queue_size
    description: "Size of the 'myqueue' queue"
    resourceType: ServiceBusQueue
    namespace: myNamespace
    queueName: myQueue
    azureMetricConfiguration:
      metricName: Size
      aggregation: Average
```

This should be more readable than before
