### ISSUE TITLE
Switch to runtime configuration YAML

### ISSUE THREAD

**Issue by tomkerkhove** [tomkerkhove/promitor#431]
As of today, all the runtime configuration is done via environment variables which is fine if you have a few of them but it feels like the list is becoming too long.

We should take a step back and see if we should go to a configuration model where we define them in YAML as well and load them at runtime, similar to how [Prometheus](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#configuration-file) and other tools approach this.

**Benefits:**
- Everything in one file which can be loaded via a volume (Docker) or config map (Kubernetes)
- Configuration can be added to source control
- Easier to read and get an idea what it is configured like
- Centralized configuration

**Downsides:**
- Harder to get started as you need to know how volumes/config maps work
	- I think we can provide the required guidance around this and/or provide default config, either in the container or docs, to use
- Existing customers need to migrate to the new model

**The (de)serialization should use the out-of-the-box capability, and not built our own as we do for the metrics, given it's pretty straight forward.**

### Checklist
- [X] Move all configuration to the structure below, except for auth information
- [x] Update all documentation on this and use an example. Location should be `/config/runtime.yaml`
- [x] Provide unit testing, where needed.
- [x] Update Docker Hub bot.
- [x] Ensure optional variables are working fine
- [x] Update Helm Chart
- [ ] Change landing page to point to v1.0

### Configuration Example
This configuration should include everything from [our configuration docs](https://promitor.io/configuration/) except for authentication config which would still be via environment variables.
```yaml
server:
  httpPort: 80
prometheus:
  scrapeEndpoint:
    baseUriPath: /prometheus/scrape
metricsConfiguration:
  absolutePath: /config/metrics-declaration.yaml
logging:
  applicationInsights:
    instrumentationKey: ABC
    isEnabled: true
  containerLogs:
    isEnabled: true
    verbosity: warning
featureFlags:
  metrics:
    disableTimestamps: true # false by default
```
