### ISSUE TITLE
Load StorageQueue SAS Tokens From Secret

### ISSUE THREAD

**Issue by barakAtSoluto** [tomkerkhove/promitor#514]
Currently the metrics configuration is loaded from a Config Map object. 
When querying an Azure StorageQueue (or other storage account types I assume) you must provide sasToken. 
There should be a way to pass that token in a more secure fashion.

### Specification

- [ ] SaS tokens are not passed in clear text via configMap

**Comment by tomkerkhove** [comment]
Fair ask.

Would it make sense if you can pass hard-coded value or a name of env variable to consume which is defined in the config file? Or how would you prefer this?

**Comment by tomkerkhove** [comment]
My initial thinking would be something along these lines.

Default should use an environment variable following this approach
```yaml
name: demo_queue_size
description: "Amount of messages in the 'orders' queue"
resourceType: StorageQueue
accountName: promitor
queueName: orders
sasToken:
  environmentVariable: AZURE_STORAGE_SAS_TOKEN
azureMetricConfiguration:
  metricName: MessageCount
  aggregation:
    type: Total
```

However, in some scenarios a fixed one could make sense.

It would look like this then:
```yaml
name: demo_queue_size
description: "Amount of messages in the 'orders' queue"
resourceType: StorageQueue
accountName: promitor
queueName: orders
sasToken:
  value: ?sv=2015-04-05&st=2015-04-29T22%3A18%3A26Z&se=2015-04-30T02%3A23%3A26Z&sr=b&sp=rw&sip=168.1.5.60-168.1.5.70&spr=https&sig=Z%2FRHIX5Xcg0Mq2rqI3OlWTjEg2tYkboXr1P9ZUXDtkk%3D
azureMetricConfiguration:
  metricName: MessageCount
  aggregation:
    type: Total
```
