### ISSUE TITLE
Do not log SAS Tokens for Azure Storage

### ISSUE THREAD

**Issue by tomkerkhove** [tomkerkhove/promitor#530]
Do not log SAS Tokens for Azure Storage.

**Comment by tomkerkhove** [comment]
@barakAtSoluto where exactly was this logged? Was it at start-up?

**Comment by tomkerkhove** [comment]
Start-up logs are now sanitizing the SAS tokens:
```yaml
- accountName: promitor
  queueName: orders
  sasToken:
    rawValue: '***'
  resourceType: StorageQueue
  azureMetricConfiguration:
    metricName: MessageCount
    aggregation:
      type: Total
      interval: 00:05:00
  description: Approximate amount of messages in 'orders' queue (determined with StorageQueue provider)
  name: demo_azurestoragequeue_queue_size
  resourceGroupName: promitor
  scraping:
    schedule: 0 */2 * ? * *
```

Did you find it anywhere else @barakAtSoluto? If not, I think we can close this.

/remind me in 7 days to close this issue unless @barakAtSoluto comes up with another flaw.
