### ISSUE TITLE
Not able to use Generic Scraper with PostgreSQL

### ISSUE THREAD

**Issue by cnadolny** [tomkerkhove/promitor#591]
## Expected Behavior
When using the Generic Metrics Config, I should be able to view metrics from PostgreSQL. As far as I can tell I'm using the correct settings, but please let me know if this is a user error :)

## Actual Behavior
I get back a response on localhost:8080/metrics, but the actual value of my metric is 0, even though there is data under the Azure Metrics Portal for the resource.
```
# HELP generic_postgresql_scraper Amount of active messages of the 'generic_postgresql_scraper'
# TYPE generic_postgresql_scraper gauge
generic_postgresql_scraper{resource_uri="subscriptions/<sub-id>/resourceGroups/RG/providers/Microsoft.DBforPostgreSQL/servers/claudia-postgresql"} 0 1560552019824
# HELP promitor_ratelimit_arm Indication how many calls are still available before Azure Resource Manager is going to throttle us.
# TYPE promitor_ratelimit_arm gauge
promitor_ratelimit_arm{tenant_id="<tenant-id>",subscription_id="<sub-id>",app_id="<app-id>"} 11959 1560552019771
```

## Steps to Reproduce the Problem

  1. Create Azure PostgreSQL db
  2. Create metrics config 
  3. Deploy Promitor

## Configuration
Provide insights in the configuration that you are using:
Used default scraping schedule

I used this as a reference for what metrics to scrape:
https://docs.microsoft.com/en-us/azure/azure-monitor/platform/metrics-supported#microsoftdbforpostgresqlservers

and here is my YAML:
```yaml
metrics:
  - name: "generic_postgresql_scraper"
    description: "test"
    resourceType: "Generic"
    resourceUri: "Microsoft.DBforPostgreSQL/servers/claudia-postgresql"
    azureMetricConfiguration:
      metricName: "cpu_percent"
      aggregation:
        Type: "Average"
```

## Specifications

  - Version: Latest helm chart
  - Platform: Windows
  - Subsystem: WSL
