### ISSUE TITLE
Provide better configuration deserialization & validation at startup

### ISSUE THREAD

**Issue by tomkerkhove** [tomkerkhove/promitor#592]
Provide better configuration deserialization & validation at startup.

An example of this came up in #591 where everything seemed ok but in really there was a deserialization issue which was not blocked given we don't have mandatory field validation.

Configuration was:
```yaml
metrics:
  - name: "generic_postgresql_scraper"
    description: "test"
    resourceType: "Generic"
    resourceUri: "Microsoft.DBforPostgreSQL/servers/promitor"
    azureMetricConfiguration:
      metricName: "cpu_percent"
      aggregation:
        Type: "Average"
```

Which should resolve in something along the lines of:
```json
[
  {
    "resourceType": "Generic",
    "resourceUri": "Microsoft.DBforPostgreSQL/servers/promitor",
    "azureMetricConfiguration": {
      "metricName": "cpu_percent",
      "aggregation": {
        "type": "None",
        "interval": "00:05:00"
      }
    },
    "description": "test",
    "name": "generic_postgresql_scraper",
    "resourceGroupName": "promitor",
    "scraping": {
      "schedule": "0 * * ? * *"
    }
  }
]
```

Note that `azureMetricConfiguration.aggregation.type` is `none` since the configuration has `Type` rather than `type`. We should not ignore this.
