### ISSUE TITLE
Provide capability to specify custom labels per metric

### ISSUE THREAD

**Issue by tomkerkhove** [tomkerkhove/promitor#603]
Provide capability to specify custom labels per metric which are included for every scrape result.

This will be configured in metric declaration via the `labels` node:
```yaml
azureMetadata:
  tenantId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
  subscriptionId: yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy
  resourceGroupName: promitor
metricDefaults:
  aggregation:
    interval: 00:05:00
  scraping:
    # Every minute
    schedule: "0 * * ? * *"
metrics:
  - name: demo_queue_size
    description: "Amount of active messages of the 'myqueue' queue"
    resourceType: ServiceBusQueue
    namespace: promitor-messaging
    queueName: orders
    labels:
      app: promitor
    azureMetricConfiguration:
      metricName: ActiveMessages
      aggregation:
        type: Total
        interval: 00:15:00
```
