### ISSUE TITLE
Provide versioning for metrics declaration spec

### ISSUE THREAD

**Issue by tomkerkhove** [tomkerkhove/promitor#646]
As of today, if we want to make breaking changes to the metrics declaration that means we need to ship a new version of Promitor. #513 is an example of this.

By providing versioned specifications, we can avoid this scenario allowing users to configure with the latest approach or stick to an older one in case they cannot move yet.

## Checklist

- [x] Change metrics declaration usage & deserialization
- [ ] Update Helm chart to create valid metrics declaration

## Specification

This issue will be a breaking change where we introduce `version`:
```yaml
version: v1
azureMetadata:
  tenantId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
  <redacted>
```
