### ISSUE TITLE
Helm chart does not inject resources correctly

### ISSUE THREAD

**Issue by tomkerkhove** [tomkerkhove/promitor#695]
When given the following input to our Helm chart:
```yaml
metrics:
  - name: promitor_demo_servicebusqueue_queue_size
    description: "Amount of active messages of the 'orders' queue (determined with ServiceBusQueue provider)"
    resourceType: ServiceBusQueue
    azureMetricConfiguration:
      metricName: ActiveMessages
      aggregation:
        type: Average
        # Optionally override the default aggregation interval (metricDefaults.aggregation.interval)
        interval: 00:15:00
    resources:
      - namespace: promitor-messaging
        queueName: orders
```

It will not correctly inject the metrics in the config map:
```yaml
metrics:
  - azureMetricConfiguration:
      aggregation:
        interval: "00:15:00"
        type: Average
      metricName: ActiveMessages
    description: Amount of active messages of the 'orders' queue (determined with ServiceBusQueue
      provider)
    name: promitor_demo_servicebusqueue_queue_size
    resourceType: ServiceBusQueue
    resources:
    - namespace: promitor-messaging
      queueName: orders
```
*Note the lack of a tab for the resource*

The issue will lie in our tpl statement I think:
`{{ tpl $metrics . | indent 6 }}`

Relates to #513
