### ISSUE TITLE
Azure SQL scraper: All databases in a server

### ISSUE THREAD

**Issue by chelnak** [tomkerkhove/promitor#757]
Is it possible to enhance the current AzureSQL scraper that is in master to enable all databases within a server to be scraped for a given metric?

Not sure when this feature will make it to the official release but it would be nice as it gives the user the ability to see the same metric across many databases.. reducing config required.

Adding @adamconnelly to this conversation as it seems that the PR was from him.

**Comment by tomkerkhove** [comment]
We have similar issues open (Storage, Service Bus) but it's not sure yet when we will implement them.

The SQL scraper will be part of v1.1 but this will not make the cut, however, I'm pretty sure we will implement this at some point.

Will have a look at this later on to see how we can leverage this but am open for contributions as well.

**Comment by chelnak** [comment]
Sounds good. More than happy to PR something if I can get some time.

**Comment by adamconnelly** [comment]
@chelnak just adding my thoughts since you tagged me.

- I think it makes a lot of sense, but it's probably worth looking at this along with some other resources like Tom mentioned so that the configuration format ends up being simple and consistent.
- It's also going to add additional API calls in order to find all the databases to scrape since that information isn't currently available. Not saying this is a problem - just something to think about.
- It possibly overlaps with https://github.com/tomkerkhove/promitor/issues/512, which talks about being able to use (for example) Azure Resource Tags to tag resources that should be scraped. Maybe it's worth trying to mock out a few possible config examples to figure out how different scenarios would work?

I think it sounds like a good idea though, and one that would be useful to us at my work.

**Comment by tomkerkhove** [comment]
Certainly agree that this is a good idea, but think it's best to do an overall look at how to approach this.

Bottom line - This will come, but we'll have to wait a bit indeed.

**Comment by chelnak** [comment]
Yep agree too. Thanks the replies

**Comment by tomkerkhove** [comment]
You can now list multiple DBs for the same metric:

```yaml
name: azure_sql_database_dtu_consumption_percent
description: "The DTU consumption percentage used by an Azure SQL Database."
resourceType: SqlDatabase
azureMetricConfiguration:
  metricName: dtu_consumption_percent
  aggregation:
    type: Average
resources:
- serverName: promitor-sql-server
  databaseName: promitor-db-1
- serverName: promitor-sql-server
  databaseName: promitor-db-2
- serverName: promitor-sql-server
  databaseName: promitor-db-3
- serverName: promitor-sql-server
  databaseName: promitor-db-4
- serverName: promitor-sql-server
  databaseName: promitor-db-5
- serverName: promitor-sql-server
  databaseName: promitor-db-6
```

Is it ok for you if we close this issue or do you have more needs?
