### ISSUE TITLE
Unable to specify multiple CosmosDB resource groups

### ISSUE THREAD

**Issue by ricardoalcazar** [tomkerkhove/promitor#794]
## Expected Behavior
Display metrics from multiple resource group/databases using a single Promitor instance.

## Actual Behavior
An exception is thrown indicating database is not available in (default) resource group.

## Steps to Reproduce the Problem

  1. Set azureMetadata.resourceGroupName attribute (default RG)
  2. Add metrics.name.resourceGroupName attribute (override RG)
  3. Specify metrics.name.resources.dbName

## Configuration
Provide insights in the configuration that you are using:
- Configured scraping schedule: 

<details>
<summary>Used scraping configuration</summary>

```yaml

version: v1
azureMetadata:
  tenantId: --omitted--
  subscriptionId: --omitted--
  resourceGroupName: DV-GROUP1-RG
metricDefaults:
  scraping:
    schedule: "0 * * ? * *" # every minute
  aggregation:
    interval: 00:00:30
metrics:
  - name: azure_cosmos_db_provisioned_throughput_activities_cdb
    description: "Demo cosmos query"
    resourceType: CosmosDb
    resourceGroupName: DEV-GROUP2-RG
    azureMetricConfiguration:
      metricName: ProvisionedThroughput 
      aggregation:
        type: Maximum
    resources:
    - dbName: dev-activities-cdb
  - name: azure_cosmos_db_provisioned_throughput
    description: "Demo cosmos query"
    resourceType: CosmosDb
    azureMetricConfiguration:
      metricName: ProvisionedThroughput 
      aggregation:
        type: Maximum
    resources:
    - dbName: dev-cdb

```
  
</details>

## Specifications

  - Version: 1
  - Platform: Linux/Ubuntu
  - Subsystem:
