### ISSUE TITLE
Provide capability to filter out a segment of a metric dimension

### ISSUE THREAD

**Issue by tomkerkhove** [tomkerkhove/promitor#809]
As of #81 you can consume multi-dimensional metrics for which a new label will be added.

Example:
```
# HELP promitor_demo_container_cpu The CPU of our containers in a container group.
# TYPE promitor_demo_container_cpu gauge
promitor_demo_container_cpu{resource_group="promitor-sources",subscription_id="0f9d7fea-99e8-4768-8672-06a28514f77e",resource_uri="subscriptions/0f9d7fea-99e8-4768-8672-06a28514f77e/resourceGroups/promitor-sources/providers/Microsoft.ContainerInstance/containerGroups/promitor-container-group",instance_name="promitor-container-group",containerName="aci-tutorial-app"} 0 1578063614577
promitor_demo_container_cpu{resource_group="promitor-sources",subscription_id="0f9d7fea-99e8-4768-8672-06a28514f77e",resource_uri="subscriptions/0f9d7fea-99e8-4768-8672-06a28514f77e/resourceGroups/promitor-sources/providers/Microsoft.ContainerInstance/containerGroups/promitor-container-group",instance_name="promitor-container-group",containerName="aci-tutorial-sidecar"} 1 1578063613819
```

But if you have 1000 instances of a single dimension, you might want to filter out some of them.

We should provide the capability to filter based on configuration. What this filter looks like is still TBD.

**Comment by locmai** [comment]
Read through the related tickets, not sure why you dropped the target_name in the #81? As my understanding (please correct me if I were wrong :D ):
We have:
- Only 1 Splitting Filter which is the current implementation with dimension.Name as the base dimension.
- Multiple filter with: Property, Operator (let's say we might only give the `eq` option) and multiple values.

So in the doc https://docs.microsoft.com/en-us/azure/azure-monitor/essentials/rest-api-walkthrough#retrieve-metric-definitions-multi-dimensional-api , the example filter for storage account is:

```
$filter = "APIName eq '*' and GeoType eq 'Primary'"
```

Resulted in:
APIName is the main splitting dimension, and GeoType is the property filer

<img width="616" alt="Screen Shot 2021-10-10 at 05 11 36" src="https://user-images.githubusercontent.com/27542393/136674934-e02ebe15-8b50-4a50-ac42-a3ff5efe3de8.png">
: 

So maybe something like this would work right? 

```
  dimension:
    name: APName
    #new config
    segmentFilters: 
    - name: GeoType
       targetValues:
       - Primary
       - Secondary
```

We will have 2 dimensional metric filters:
```
$filterForPrimary = "APIName eq '*' and GeoType eq 'Primary'"
$filterForSecondary = "APIName eq '*' and GeoType eq 'Secondary'"
```

It might get a bit more tangled with more segment filters added:

```
  dimension:
    name: APName
    #new config
    segmentFilters: 
    - name: GeoType
       targetValues:
       - Primary
       - Secondary
    - name: ResponseType
       targetValues:
       - Success
```

But I think we could work it out.

**Comment by locmai** [comment]
@tomkerkhove could you take a look at the above comment?

*Also* I just realized that we could split by multi-dimension at the same time:

```
APIName eq '*' and GeoType eq '*'"
```

So we would expect that we could add various dimensions the same way we did for the base dimension:

```
  dimensions:
    - name: APIName
       filters: []
    - name: GeoType
```

^ This specs would give us metrics with {APIName="<api-name", GeoType="<geo-type">} labels!
