### ISSUE TITLE
Provide support for multi-dimensional metrics

### ISSUE THREAD

**Issue by tomkerkhove** [tomkerkhove/promitor#81]
Provide support for scraping multi-dimensional metrics.

Configuration should be expanded to include optional `dimension` information.

This should cover:
- Name of the dimension to use _(mandatory)_
- Target of partition in dimension you are interested in _(optional)_

The reported metric in the scraping endpoint should use labels to report the metric with a general name but labeled for every dimension regardless if a target was specified or not.

Names are just examples, open for feedback!

### Example
```yaml
name: demo_containerinstances_cpu
description: "Average cpu usage of our 'promitor-container-instance' container instance"
resourceType: ContainerInstance
containerGroup: promitor-container-instance
azureMetricConfiguration:
  metricName: CpuUsage
  aggregation:
    type: Average
  dimension:
    name: containerName # name of the dimension to split on
    target: redis-single-node # name of the targetted partition in the dimension you're interested in
```

### Portal
You can see this in action in the Azure Portal:
![image](https://user-images.githubusercontent.com/4345663/55037498-3b219700-4fdb-11e9-9bd3-b11bf6ee5d25.png)
