### ISSUE TITLE
[Chart] Service/Pod created in promitor chart should leverage "inside Kubernetes" prometheus service discovery for registering metrics

### ISSUE THREAD

**Issue by hajdukd** [tomkerkhove/promitor#861]
### Specification

Prometheus inside Kubernetes is able to scrap headless services or pods with appropriate annotations on them.

The chart should either allow specifying those by the user or should already contain those with a simple boolean check whether it should be enabled.

### API Specification

```yaml
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
```
