### ISSUE TITLE
Logging does not show root cause

### ISSUE THREAD

**Issue by stigok** [tomkerkhove/promitor#927]
I am having problems finding the cause of printed errors. They provide information about what the results were, but not what caused it, or what paths were attempted.

In the case of AzureMonitor, when I had invalid role permissions, I was getting
```
fail: Promitor.Integrations.AzureMonitor.Logging.AzureMonitorIntegrationLogger[0]              
      Exception in 5: Microsoft.Azure.Management.Monitor.Fluent.Models.ErrorResponseException: Operation returned an invalid status code 'Forbidden'
```

This tells me that *some url* probably received an HTTP 403, but that's all I know. I think the URL, status code and the actual error message from the API would of interest here.

When I had configured the proper roles, I was getting the following error
```
fail: Promitor.Integrations.AzureMonitor.Logging.AzureMonitorIntegrationLogger[0]
      Exception in 5: Microsoft.Azure.Management.Monitor.Fluent.Models.ErrorResponseException: Operation returned an invalid status code 'NotFound'
```

I don't know what isn't found. More verbosity in the logs would be nice. Or am I missing a flag?

## Configuration

Config
```yaml
server:
  httpPort: 8080
prometheus:
  # metricUnavailableValue: NaN
  # enableMetricTimestamps: true
  scrapeEndpoint:
    baseUriPath: /metrics
metricsConfiguration:
  absolutePath: /config/metrics-declaration.yaml
telemetry:
  containerLogs:
    isEnabled: false
  defaultVerbosity: debug

azureMonitor:
  logging:
    informationLevel: BodyAndHeaders
    isEnabled: true
```

Metrics
```yaml
version: v1
azureMetadata:
  tenantId: xxx
  subscriptionId: xxx
  resourceGroupName: promitor
metricDefaults:
  aggregation:
    interval: 00:05:00
  scraping:
    # Every minute
    schedule: "0 * * ? * *"

metrics:
- name: promitor_demo_azuresqlmanagedinstance_nodes
  description: "The amount of nodes for an Azure SQL Managed Instance."
  resourceType: SqlManagedInstance
  azureMetricConfiguration:
    metricName: virtual_core_count
    aggregation:
      type: Average
  resources:
  - instanceName: my-special-postgres-instance
```

## Specifications

  - Version: 1.4.0
  - Platform: Docker on Linux
  - Subsystem:
