### ISSUE TITLE
Allow a default set of labels in metricDefaults

### ISSUE THREAD

**Issue by stigok** [tomkerkhove/promitor#933]
Allow a default set of labels in `metricDefaults`. In our use-case we'd like to do the following:

```
  metricDefaults:                                                                                                                                                                           
    aggregation:                                                                                                                                                                            
      interval: 00:05:00                                                                                                                                                                    
    scraping:                                                                                                                                                                               
      schedule: 0 * * ? * *
    labels:
      metrics-source: promitor
```
