### ISSUE TITLE
Allow different subscriptions per metric

### ISSUE THREAD

**Issue by stigok** [tomkerkhove/promitor#934]
Allow different subscriptions per metric. I don't know if `subscriptionId` is the way to go, or if it would work with `subscriptionName`?

```
- name: azure_postgre_sql_memory_percent
  description: Server memory usage percentage
  resourceType: PostgreSql
  azureMetricConfiguration:
    metricName: memory_percent
    aggregation:
      type: Average
      interval: 00:05:00
  resources:
  - serverName: foobar
    resourceGroupName: barfoo
    subscriptionId: <sub id>
```
